# -*- coding: utf-8 -*-
ARGUMENTS = [
    {"num":1,"key":"cosmological",
     "title":{"en":"The Cosmological Argument","fr":"L'Argument Cosmologique","es":"El Argumento Cosmológico"},
     "content":{"en":"Everything that begins to exist has a cause. The universe began to exist — confirmed by the Big Bang. Therefore, the universe has a cause beyond space, time, and matter. That uncaused cause is God.",
                "fr":"Tout ce qui commence à exister a une cause. L'univers a commencé à exister — confirmé par le Big Bang. Donc l'univers a une cause au-delà de l'espace, du temps et de la matière.",
                "es":"Todo lo que comienza a existir tiene una causa. El universo comenzó a existir — confirmado por el Big Bang. Por lo tanto, el universo tiene una causa más allá del espacio, el tiempo y la materia."},
     "question":{"en":"If the universe had a beginning, who set it in motion?","fr":"Si l'univers a eu un commencement, qui l'a mis en mouvement ?","es":"Si el universo tuvo un comienzo, ¿quién lo puso en movimiento?"},
     "verse_ar":"أَمْ خُلِقُوا مِنْ غَيْرِ شَيْءٍ أَمْ هُمُ الْخَالِقُونَ",
     "verse_en":"Or were they created by nothing, or were they the creators?",
     "verse_ref":"Quran 52:35"},

    {"num":2,"key":"finetuning",
     "title":{"en":"The Fine-Tuning Argument","fr":"Le Réglage Fin","es":"El Ajuste Fino"},
     "content":{"en":"The physical constants of the universe are calibrated with breathtaking precision. Change gravity by one part in 10^40 and no stars form. This precision is not luck — it is intention.",
                "fr":"Les constantes physiques de l'univers sont calibrées avec une précision stupéfiante. Cette précision n'est pas de la chance — c'est une intention.",
                "es":"Las constantes físicas del universo están calibradas con una precisión asombrosa. Esta precisión no es suerte — es intención."},
     "question":{"en":"Is such precision random chance — or deliberate design?","fr":"Une telle précision est-elle du hasard — ou un dessein délibéré ?","es":"¿Es esa precisión azar — o diseño deliberado?"},
     "verse_ar":"وَخَلَقَ كُلَّ شَيْءٍ فَقَدَّرَهُ تَقْدِيرًا",
     "verse_en":"And He created all things and determined them with precise determination.",
     "verse_ref":"Quran 25:2"},

    {"num":3,"key":"design",
     "title":{"en":"The Argument from Design","fr":"L'Argument du Dessein","es":"El Argumento del Diseño"},
     "content":{"en":"From the bacterial flagellum to the human eye, biology displays machines of irreducible complexity. A watch implies a watchmaker — how much more so a living cell?",
                "fr":"Du flagelle bactérien à l'œil humain, la biologie révèle des machines d'une complexité irréductible. Une montre implique un horloger — combien plus une cellule vivante ?",
                "es":"Desde el flagelo bacteriano hasta el ojo humano, la biología muestra máquinas de complejidad irreducible. Un reloj implica un relojero — ¿cuánto más una célula viva?"},
     "question":{"en":"Could a machine more complex than a city build itself?","fr":"Une machine plus complexe qu'une ville peut-elle se construire seule ?","es":"¿Puede una máquina más compleja que una ciudad construirse sola?"},
     "verse_ar":"صُنْعَ اللَّهِ الَّذِي أَتْقَنَ كُلَّ شَيْءٍ",
     "verse_en":"The handiwork of Allah, who perfected all things.",
     "verse_ref":"Quran 27:88"},

    {"num":4,"key":"dna",
     "title":{"en":"The Argument from DNA Information","fr":"L'Argument de l'ADN","es":"El Argumento del ADN"},
     "content":{"en":"Every human cell contains ~3 billion base pairs of coded information — roughly 750 megabytes. Information is not matter. It requires a mind. Where there is a code, there is a coder.",
                "fr":"Chaque cellule humaine contient ~3 milliards de paires de bases d'information codée. L'information n'est pas de la matière. Elle exige un esprit. Où il y a un code, il y a un codeur.",
                "es":"Cada célula humana contiene ~3 mil millones de pares de bases de información codificada. La información no es materia. Exige una mente. Donde hay código, hay un codificador."},
     "question":{"en":"Did the first cell arrive with a library already written inside it?","fr":"La première cellule est-elle arrivée avec une bibliothèque déjà écrite ?","es":"¿Llegó la primera célula con una biblioteca ya escrita dentro?"},
     "verse_ar":"اقْرَأْ بِاسْمِ رَبِّكَ الَّذِي خَلَقَ",
     "verse_en":"Read in the name of your Lord who created.",
     "verse_ref":"Quran 96:1"},

    {"num":5,"key":"consciousness",
     "title":{"en":"The Argument from Consciousness","fr":"L'Argument de la Conscience","es":"El Argumento de la Conciencia"},
     "content":{"en":"We experience thoughts, colors, love, and pain — inner experiences that no amount of chemistry can explain. Matter has size and weight; thoughts do not. If the mind were only matter, no one could ever know it.",
                "fr":"Nous éprouvons des pensées, des couleurs, l'amour — des expériences intérieures qu'aucune chimie n'explique. La matière a taille et poids ; les pensées non.",
                "es":"Experimentamos pensamientos, colores, amor — experiencias internas que ninguna química explica. La materia tiene tamaño y peso; los pensamientos no."},
     "question":{"en":"Can water be wet, and yet no one be there to feel it?","fr":"L'eau peut-elle être mouillée, sans personne pour la sentir ?","es":"¿Puede el agua estar mojada, sin nadie que la sienta?"},
     "verse_ar":"وَنَفَخْتُ فِيهِ مِن رُّوحِي",
     "verse_en":"And I breathed into him of My spirit.",
     "verse_ref":"Quran 15:29"},

    {"num":6,"key":"logic",
     "title":{"en":"The Argument from Reason","fr":"L'Argument de la Raison","es":"El Argumento de la Razón"},
     "content":{"en":"Mathematical and logical truths (1+1=2, no square circle) are immaterial, universal, eternal. They are not brain states. Blind matter cannot produce necessary truths. Only a necessary Mind can ground them.",
                "fr":"Les vérités mathématiques et logiques sont immatérielles, universelles, éternelles. Elles ne sont pas des états cérébraux. La matière aveugle ne produit pas des vérités nécessaires.",
                "es":"Las verdades matemáticas y lógicas son inmateriales, universales, eternas. No son estados cerebrales. La materia ciega no produce verdades necesarias."},
     "question":{"en":"Where does 2+2=4 exist — in a place, or in a Mind?","fr":"Où existe 2+2=4 — dans un lieu, ou dans un Esprit ?","es":"¿Dónde existe 2+2=4 — en un lugar, o en una Mente?"},
     "verse_ar":"وَكُلَّ شَيْءٍ أَحْصَيْنَاهُ فِي إِمَامٍ مُّبِينٍ",
     "verse_en":"And all things We have enumerated in a clear register.",
     "verse_ref":"Quran 36:12"},

    {"num":7,"key":"moral",
     "title":{"en":"The Moral Argument","fr":"L'Argument Moral","es":"El Argumento Moral"},
     "content":{"en":"We all sense that torturing a child is objectively evil — not merely taboo. Objective moral values require an objective foundation, beyond culture and preference. That foundation is God.",
                "fr":"Nous sentons tous que torturer un enfant est objectivement mauvais — pas seulement tabou. Les valeurs morales objectives nécessitent un fondement objectif.",
                "es":"Todos sentimos que torturar a un niño es objetivamente malo — no solo tabú. Los valores morales objetivos necesitan un fundamento objetivo."},
     "question":{"en":"If morality is just opinion, why do we argue that some things are truly wrong?","fr":"Si la morale n'est qu'opinion, pourquoi débattons-nous de ce qui est vraiment mal ?","es":"Si la moral es solo opinión, ¿por qué discutimos qué está realmente mal?"},
     "verse_ar":"وَنَفْسٍ وَمَا سَوَّاهَا فَأَلْهَمَهَا فُجُورَهَا وَتَقْوَاهَا",
     "verse_en":"And by the soul and He who proportioned it — He inspired it with its wickedness and its righteousness.",
     "verse_ref":"Quran 91:7-8"},

    {"num":8,"key":"fitrah",
     "title":{"en":"The Argument of the Fitrah","fr":"L'Argument de la Fitrah","es":"El Argumento de la Fitrah"},
     "content":{"en":"Every human — in every culture, in every era — reaches out to something beyond. Even atheists cry 'Oh God!' when terror strikes. This universal instinct, the fitrah, points to our Maker.",
                "fr":"Chaque être humain tend vers quelque chose au-delà. Même les athées crient 'Oh mon Dieu !' dans la terreur. Cet instinct universel, la fitrah, pointe vers notre Créateur.",
                "es":"Todo ser humano busca algo más allá. Incluso los ateos gritan '¡Dios mío!' en el terror. Este instinto universal, la fitrah, apunta a nuestro Creador."},
     "question":{"en":"Why does the soul search, if nothing is there?","fr":"Pourquoi l'âme cherche-t-elle, si rien n'est là ?","es":"¿Por qué busca el alma, si no hay nada?"},
     "verse_ar":"فَأَقِمْ وَجْهَكَ لِلدِّينِ حَنِيفًا ۚ فِطْرَتَ اللَّهِ الَّتِي فَطَرَ النَّاسَ عَلَيْهَا",
     "verse_en":"So direct your face toward the religion, inclining to truth — the fitrah of Allah upon which He created the people.",
     "verse_ref":"Quran 30:30"},

    {"num":9,"key":"contingency",
     "title":{"en":"The Argument from Contingency","fr":"L'Argument de la Contingence","es":"El Argumento de la Contingencia"},
     "content":{"en":"Every thing we see could have been otherwise — it might not have existed. Such things need a reason outside themselves. An infinite chain of contingent things explains nothing. There must be one Necessary Being.",
                "fr":"Tout ce que nous voyons aurait pu ne pas exister. De telles choses ont besoin d'une raison hors d'elles-mêmes. Il doit exister un Être Nécessaire.",
                "es":"Todo lo que vemos podría no haber existido. Tales cosas necesitan una razón fuera de sí mismas. Debe existir un Ser Necesario."},
     "question":{"en":"Why is there something rather than nothing?","fr":"Pourquoi y a-t-il quelque chose plutôt que rien ?","es":"¿Por qué hay algo en lugar de nada?"},
     "verse_ar":"اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ",
     "verse_en":"Allah — there is no deity except Him, the Ever-Living, the Sustainer of existence.",
     "verse_ref":"Quran 2:255"},

    {"num":10,"key":"math",
     "title":{"en":"The Argument from Mathematics","fr":"L'Argument des Mathématiques","es":"El Argumento de las Matemáticas"},
     "content":{"en":"Physics runs on mathematics — elegant, invisible, eternal formulas that describe the cosmos. Why is the universe mathematical? Because it was written by a Mathematician.",
                "fr":"La physique fonctionne grâce aux mathématiques — des formules élégantes, invisibles, éternelles. Pourquoi l'univers est-il mathématique ? Parce qu'il fut écrit par un Mathématicien.",
                "es":"La física funciona con matemáticas — fórmulas elegantes, invisibles, eternas. ¿Por qué es matemático el universo? Porque fue escrito por un Matemático."},
     "question":{"en":"Why does the universe obey equations no one invented?","fr":"Pourquoi l'univers obéit-il à des équations que personne n'a inventées ?","es":"¿Por qué obedece el universo ecuaciones que nadie inventó?"},
     "verse_ar":"وَإِن مِّن شَيْءٍ إِلَّا عِندَنَا خَزَائِنُهُ",
     "verse_en":"And there is not a thing but that with Us are its depositories.",
     "verse_ref":"Quran 15:21"},

    {"num":11,"key":"beauty",
     "title":{"en":"The Argument from Beauty","fr":"L'Argument de la Beauté","es":"El Argumento de la Belleza"},
     "content":{"en":"Beauty moves us — a sunset, a violin concerto, a mother's smile. If beauty is just chemistry, why does it break our hearts? Beauty is a language spoken by the unseen.",
                "fr":"La beauté nous émeut — un coucher de soleil, un concerto, un sourire maternel. Si la beauté n'était que chimie, pourquoi nous brise-t-elle le cœur ?",
                "es":"La belleza nos conmueve — un atardecer, un concierto, la sonrisa de una madre. Si la belleza fuera solo química, ¿por qué nos rompe el corazón?"},
     "question":{"en":"Where does the human capacity for awe come from?","fr":"D'où vient la capacité humaine de s'émerveiller ?","es":"¿De dónde viene la capacidad humana de asombrarse?"},
     "verse_ar":"إِنَّ اللَّهَ جَمِيلٌ يُحِبُّ الْجَمَالَ",
     "verse_en":"Indeed Allah is Beautiful and He loves beauty.",
     "verse_ref":"Hadith — Sahih Muslim"},

    {"num":12,"key":"providence",
     "title":{"en":"The Argument from Providence","fr":"L'Argument de la Providence","es":"El Argumento de la Providencia"},
     "content":{"en":"From the newborn's milk to the bees' honey, from rain to seed — every creature receives exactly what it needs. This universal sustenance is not accident. It is provision from a Provider.",
                "fr":"Du lait du nouveau-né au miel des abeilles — chaque créature reçoit exactement ce dont elle a besoin. Cette subsistance universelle n'est pas accident.",
                "es":"Desde la leche del recién nacido hasta la miel de las abejas — cada criatura recibe exactamente lo que necesita. Este sustento universal no es accidente."},
     "question":{"en":"Who feeds the bird that no hand feeds?","fr":"Qui nourrit l'oiseau qu'aucune main ne nourrit ?","es":"¿Quién alimenta al pájaro que ninguna mano alimenta?"},
     "verse_ar":"وَمَا مِن دَابَّةٍ فِي الْأَرْضِ إِلَّا عَلَى اللَّهِ رِزْقُهَا",
     "verse_en":"And there is no creature on earth but that upon Allah is its provision.",
     "verse_ref":"Quran 11:6"},

    {"num":13,"key":"revelation",
     "title":{"en":"The Argument from Revelation","fr":"L'Argument de la Révélation","es":"El Argumento de la Revelación"},
     "content":{"en":"The Quran, revealed 14 centuries ago, contains scientific, historical, and linguistic signs no human could produce. Its preservation is unmatched in history. A book like this points to an Author beyond time.",
                "fr":"Le Coran, révélé il y a 14 siècles, contient des signes qu'aucun être humain ne pouvait produire. Sa préservation est inégalée. Un tel livre pointe vers un Auteur au-delà du temps.",
                "es":"El Corán, revelado hace 14 siglos, contiene signos que ningún humano pudo producir. Su preservación es inigualable. Un libro así apunta a un Autor más allá del tiempo."},
     "question":{"en":"Could a desert merchant write a book that defeats 14 centuries of challenge?","fr":"Un marchand du désert pouvait-il écrire un livre défiant 14 siècles ?","es":"¿Podría un mercader del desierto escribir un libro que desafía 14 siglos?"},
     "verse_ar":"قُل لَّئِنِ اجْتَمَعَتِ الْإِنسُ وَالْجِنُّ عَلَىٰ أَن يَأْتُوا بِمِثْلِ هَٰذَا الْقُرْآنِ لَا يَأْتُونَ بِمِثْلِهِ",
     "verse_en":"Say: If mankind and jinn gathered to produce the like of this Quran, they could not produce its like.",
     "verse_ref":"Quran 17:88"},

    {"num":14,"key":"consensus",
     "title":{"en":"The Argument from Universal Belief","fr":"L'Argument de la Croyance Universelle","es":"El Argumento de la Creencia Universal"},
     "content":{"en":"Over 90% of humanity across all ages has believed in a higher power. Such a universal, persistent, cross-cultural phenomenon cannot be dismissed as mass delusion. The consensus of humanity is a witness.",
                "fr":"Plus de 90% de l'humanité, à travers tous les âges, a cru en une puissance supérieure. Un phénomène aussi universel et persistant ne peut être écarté comme une illusion de masse.",
                "es":"Más del 90% de la humanidad, en todas las épocas, ha creído en un poder superior. Un fenómeno tan universal y persistente no puede descartarse como ilusión de masas."},
     "question":{"en":"Can billions of sincere seekers be wrong — in every generation?","fr":"Des milliards de chercheurs sincères peuvent-ils se tromper — à chaque génération ?","es":"¿Pueden miles de millones de buscadores sinceros estar equivocados — en cada generación?"},
     "verse_ar":"وَإِذْ أَخَذَ رَبُّكَ مِن بَنِي آدَمَ مِن ظُهُورِهِمْ ذُرِّيَّتَهُمْ وَأَشْهَدَهُمْ عَلَىٰ أَنفُسِهِمْ أَلَسْتُ بِرَبِّكُمْ ۖ قَالُوا بَلَىٰ",
     "verse_en":"And when your Lord took from the children of Adam their descendants and made them testify: 'Am I not your Lord?' They said, 'Yes.'",
     "verse_ref":"Quran 7:172"},

    {"num":15,"key":"experience",
     "title":{"en":"The Argument from Religious Experience","fr":"L'Argument de l'Expérience Religieuse","es":"El Argumento de la Experiencia Religiosa"},
     "content":{"en":"Millions across history testify to encountering God — in prayer, in suffering, in the stillness of night. A mother's testimony about her child is evidence; so is the testimony of the faithful about their Lord.",
                "fr":"Des millions à travers l'histoire témoignent avoir rencontré Dieu — dans la prière, la souffrance, le silence de la nuit. Le témoignage du croyant sur son Seigneur est une preuve.",
                "es":"Millones a lo largo de la historia testifican haber encontrado a Dios — en la oración, el sufrimiento, el silencio de la noche."},
     "question":{"en":"Why do atheists pray when their plane begins to fall?","fr":"Pourquoi les athées prient-ils quand leur avion tombe ?","es":"¿Por qué rezan los ateos cuando su avión cae?"},
     "verse_ar":"وَإِذَا مَسَّكُمُ الضُّرُّ فِي الْبَحْرِ ضَلَّ مَن تَدْعُونَ إِلَّا إِيَّاهُ",
     "verse_en":"And when adversity touches you at sea, lost are all you invoke except Him.",
     "verse_ref":"Quran 17:67"},

    {"num":16,"key":"history",
     "title":{"en":"The Argument from History","fr":"L'Argument de l'Histoire","es":"El Argumento de la Historia"},
     "content":{"en":"Every civilization — Babylon, Egypt, Greece, Rome, China — has looked upward. Prophets arose in every land. History does not record a godless civilization that thrived. This pattern is a fingerprint.",
                "fr":"Chaque civilisation a regardé vers le ciel. Des prophètes se sont levés dans chaque pays. L'histoire n'enregistre pas de civilisation athée florissante.",
                "es":"Cada civilización miró hacia arriba. Surgieron profetas en cada tierra. La historia no registra una civilización atea floreciente."},
     "question":{"en":"Why did every great civilization honor something higher?","fr":"Pourquoi chaque grande civilisation a-t-elle honoré quelque chose de plus élevé ?","es":"¿Por qué toda gran civilización honró algo superior?"},
     "verse_ar":"وَلَقَدْ بَعَثْنَا فِي كُلِّ أُمَّةٍ رَّسُولًا أَنِ اعْبُدُوا اللَّهَ",
     "verse_en":"And We certainly sent into every nation a messenger: 'Worship Allah.'",
     "verse_ref":"Quran 16:36"},
]
