# -*- coding: utf-8 -*-

def L(en, fr, es, de, it, pt):
    return {"en": en, "fr": fr, "es": es, "de": de, "it": it, "pt": pt}

JESUS_INTRO = L(
 "In Islam, Jesus (Isa) is one of the greatest prophets - born of a virgin, performing miracles by God's permission, and the Messiah promised to the Children of Israel. He is mentioned by name 25 times in the Quran, more than Muhammad himself. But he is not God, nor the son of God, nor part of a Trinity. He was a servant and messenger.",
 "En Islam, Jesus (Isa) est l'un des plus grands prophetes - ne d'une vierge, accomplissant des miracles par la permission de Dieu, et le Messie promis aux Enfants d'Israel. Il est mentionne 25 fois dans le Coran, plus que Muhammad lui-meme.",
 "En el Islam, Jesus (Isa) es uno de los mas grandes profetas - nacido de una virgen, realizando milagros con el permiso de Dios, y el Mesias prometido a los Hijos de Israel. Es mencionado 25 veces en el Coran.",
 "Im Islam ist Jesus (Isa) einer der groessten Propheten - von einer Jungfrau geboren, Wunder mit Gottes Erlaubnis wirkend. Er wird im Koran 25 Mal genannt.",
 "Nell'Islam, Gesu (Isa) e uno dei piu grandi profeti - nato da una vergine, compiendo miracoli con il permesso di Dio. E menzionato 25 volte nel Corano.",
 "No Isla, Jesus (Isa) e um dos maiores profetas - nascido de uma virgem, realizando milagres com a permissao de Deus. E mencionado 25 vezes no Alcorao.",
)

MARY_INTRO = L(
 "Mary (Maryam) is the only woman mentioned by name in the Quran - and she has an entire chapter named after her (Chapter 19). The Quran says: 'O Mary, indeed Allah has chosen you and purified you and chosen you above the women of the worlds.' (3:42)",
 "Marie (Maryam) est la seule femme mentionnee par son nom dans le Coran - et un chapitre entier porte son nom. Le Coran dit : 'O Marie, Allah t'a choisie, t'a purifiee.' (3:42)",
 "Maria (Maryam) es la unica mujer mencionada por su nombre en el Coran - y un capitulo entero lleva su nombre. El Coran dice: 'Oh Maria, Allah te ha escogido.' (3:42)",
 "Maria (Maryam) ist die einzige namentlich im Koran erwaehnte Frau - ein ganzes Kapitel ist nach ihr benannt. Der Koran sagt: 'O Maria, Allah hat dich auserwaehlt.' (3:42)",
 "Maria (Maryam) e l'unica donna menzionata per nome nel Corano - un intero capitolo porta il suo nome. Il Corano dice: 'O Maria, Allah ti ha scelta.' (3:42)",
 "Maria (Maryam) e a unica mulher mencionada pelo nome no Alcorao - um capitulo inteiro leva seu nome. O Alcorao diz: 'O Maria, Allah te escolheu.' (3:42)",
)

MESSAGE_CHRISTIANS = L(
 "We Muslims love Jesus. We love Mary. We await his return. But we do not worship him, because he himself said: 'Allah is my Lord and your Lord, so worship Him. That is the straight path.' (Quran 3:51)",
 "Nous aimons Jesus. Nous aimons Marie. Mais nous ne l'adorons pas, car il a dit : 'Allah est mon Seigneur et votre Seigneur.' (Coran 3:51)",
 "Amamos a Jesus. Amamos a Maria. Pero no lo adoramos, porque el dijo: 'Allah es mi Senor y vuestro Senor.' (Coran 3:51)",
 "Wir lieben Jesus. Wir lieben Maria. Aber wir beten ihn nicht an, denn er sagte: 'Allah ist mein Herr und euer Herr.' (Koran 3:51)",
 "Amiamo Gesu. Amiamo Maria. Ma non lo adoriamo, perche disse: 'Allah e il mio Signore e il vostro Signore.' (Corano 3:51)",
 "Amamos Jesus. Amamos Maria. Mas nao o adoramos, porque ele disse: 'Allah e meu Senhor e vosso Senhor.' (Alcorao 3:51)",
)

VERSE_REFS = [
    (3, 45), (3, 46), (3, 47), (3, 48), (3, 49), (3, 50), (3, 51), (3, 52), (3, 55),
    (4, 157), (4, 158), (4, 171),
    (5, 46), (5, 72), (5, 75), (5, 110), (5, 116),
    (19, 16), (19, 17), (19, 18), (19, 27), (19, 28), (19, 29), (19, 30),
    (21, 91),
]

COMPARISON = [
    {"topic": L("Identity of Jesus","Identite de Jesus","Identidad de Jesus","Identitaet Jesu","Identita di Gesu","Identidade de Jesus"),
     "islam": L("A Prophet, Messenger, and Messiah - a servant of God","Un prophete, messager et Messie - un serviteur de Dieu","Un profeta, mensajero y Mesias - un siervo de Dios","Ein Prophet, Gesandter und Messias - ein Diener Gottes","Un profeta, messaggero e Messia - un servo di Dio","Um Profeta, Mensageiro e Messias - um servo de Deus"),
     "gospel": L("The Son of God, second person of the Trinity","Le Fils de Dieu, deuxieme personne de la Trinite","El Hijo de Dios, segunda persona de la Trinidad","Der Sohn Gottes, zweite Person der Dreieinigkeit","Il Figlio di Dio, seconda persona della Trinita","O Filho de Deus, segunda pessoa da Trindade")},
    {"topic": L("Crucifixion","Crucifixion","Crucifixion","Kreuzigung","Crocifissione","Crucificacao"),
     "islam": L("He was not crucified - God raised him up","Il ne fut pas crucifie - Dieu l'eleva","No fue crucificado - Dios lo elevo","Er wurde nicht gekreuzigt - Gott erhob ihn","Non fu crocifisso - Dio lo elevo","Ele nao foi crucificado - Deus o elevou"),
     "gospel": L("He was crucified, died, and was buried","Il fut crucifie, mourut et fut enterre","Fue crucificado, murio y fue sepultado","Er wurde gekreuzigt, starb und wurde begraben","Fu crocifisso, mori e fu sepolto","Ele foi crucificado, morreu e foi sepultado")},
    {"topic": L("Birth","Naissance","Nacimiento","Geburt","Nascita","Nascimento"),
     "islam": L("Virgin birth - by God's command Be","Naissance virginale - par l'ordre de Dieu Sois","Nacimiento virginal - por orden de Dios Se","Jungfraeuliche Geburt - durch Gottes Befehl Sei","Nascita verginale - per ordine di Dio Sii","Nascimento virginal - por ordem de Deus Seja"),
     "gospel": L("Virgin birth - by the Holy Spirit","Naissance virginale - par le Saint-Esprit","Nacimiento virginal - por el Espiritu Santo","Jungfraeuliche Geburt - durch den Heiligen Geist","Nascita verginale - per lo Spirito Santo","Nascimento virginal - pelo Espirito Santo")},
    {"topic": L("Return","Retour","Regreso","Rueckkehr","Ritorno","Retorno"),
     "islam": L("He will return before the Day of Judgment","Il reviendra avant le Jour du Jugement","Regresara antes del Dia del Juicio","Er wird vor dem Juengsten Tag zurueckkehren","Tornera prima del Giorno del Giudizio","Ele retornara antes do Dia do Juizo"),
     "gospel": L("He will return in glory","Il reviendra dans la gloire","Regresara en gloria","Er wird in Herrlichkeit zurueckkehren","Tornera nella gloria","Ele retornara em gloria")},
    {"topic": L("Message","Message","Mensaje","Botschaft","Messaggio","Mensagem"),
     "islam": L("Worship the One God alone, without partners","Adorez le Dieu Unique seul, sans associes","Adorad al Dios Unico solo, sin asociados","Dient dem Einen Gott allein, ohne Partner","Adorate l'unico Dio, senza associati","Adorai o Unico Deus, sem associados"),
     "gospel": L("Salvation through faith in Christ","Salut par la foi en Christ","Salvacion por la fe en Cristo","Erloesung durch Glauben an Christus","Salvezza per fede in Cristo","Salvacao pela fe em Cristo")},
]

MARYAM_VERSES_PREVIEW = [
    {"num": 16, "ar": "وَاذْكُرْ فِي الْكِتَابِ مَرْيَمَ إِذِ انتَبَذَتْ مِنْ أَهْلِهَا مَكَانًا شَرْقِيًّا", "en": "And mention in the Book the story of Mary, when she withdrew from her family to a place toward the east."},
    {"num": 17, "ar": "فَاتَّخَذَتْ مِن دُونِهِمْ حِجَابًا فَأَرْسَلْنَا إِلَيْهَا رُوحَنَا فَتَمَثَّلَ لَهَا بَشَرًا سَوِيًّا", "en": "And she took a screen. Then We sent to her Our Angel, and he represented himself as a well-proportioned man."},
    {"num": 18, "ar": "قَالَتْ إِنِّي أَعُوذُ بِالرَّحْمَٰنِ مِنكَ إِن كُنتَ تَقِيًّا", "en": "She said, 'Indeed, I seek refuge in the Most Merciful from you.'"},
    {"num": 19, "ar": "قَالَ إِنَّمَا أَنَا رَسُولُ رَبِّكِ لِأَهَبَ لَكِ غُلَامًا زَكِيًّا", "en": "He said, 'I am only the messenger of your Lord to give you news of a pure boy.'"},
    {"num": 20, "ar": "قَالَتْ أَنَّىٰ يَكُونُ لِي غُلَامٌ وَلَمْ يَمْسَسْنِي بَشَرٌ", "en": "She said, 'How can I have a boy while no man has touched me?'"},
    {"num": 21, "ar": "قَالَ كَذَٰلِكِ قَالَ رَبُّكِ هُوَ عَلَيَّ هَيِّنٌ", "en": "He said, 'Thus it will be; your Lord says, It is easy for Me.'"},
    {"num": 22, "ar": "فَحَمَلَتْهُ فَانتَبَذَتْ بِهِ مَكَانًا قَصِيًّا", "en": "So she conceived him, and she withdrew with him to a remote place."},
    {"num": 23, "ar": "فَأَجَاءَهَا الْمَخَاضُ إِلَىٰ جِذْعِ النَّخْلَةِ", "en": "And the pains of childbirth drove her to the trunk of a palm tree."},
    {"num": 24, "ar": "فَنَادَاهَا مِن تَحْتِهَا أَلَّا تَحْزَنِي", "en": "But he called her from below her, 'Do not grieve; your Lord has provided beneath you a stream.'"},
    {"num": 25, "ar": "وَهُزِّي إِلَيْكِ بِجِذْعِ النَّخْلَةِ تُسَاقِطْ عَلَيْكِ رُطَبًا جَنِيًّا", "en": "And shake toward you the trunk of the palm tree; it will drop upon you ripe dates."},
    {"num": 26, "ar": "فَكُلِي وَاشْرَبِي وَقَرِّي عَيْنًا", "en": "So eat and drink and be contented."},
    {"num": 27, "ar": "فَأَتَتْ بِهِ قَوْمَهَا تَحْمِلُهُ ۖ قَالُوا يَا مَرْيَمُ لَقَدْ جِئْتِ شَيْئًا فَرِيًّا", "en": "Then she brought him to her people. They said, 'O Mary, you have done a thing unprecedented.'"},
    {"num": 28, "ar": "يَا أُخْتَ هَارُونَ مَا كَانَ أَبُوكِ امْرَأَ سَوْءٍ", "en": "O sister of Aaron, your father was not a man of evil, nor was your mother unchaste."},
    {"num": 29, "ar": "فَأَشَارَتْ إِلَيْهِ ۖ قَالُوا كَيْفَ نُكَلِّمُ مَن كَانَ فِي الْمَهْدِ صَبِيًّا", "en": "So she pointed to him. They said, 'How can we speak to one who is in the cradle?'"},
    {"num": 30, "ar": "قَالَ إِنِّي عَبْدُ اللَّهِ آتَانِيَ الْكِتَابَ وَجَعَلَنِي نَبِيًّا", "en": "Jesus said, 'Indeed, I am the servant of Allah. He has given me the Scripture and made me a prophet.'"},
    {"num": 31, "ar": "وَجَعَلَنِي مُبَارَكًا أَيْنَ مَا كُنتُ", "en": "And He has made me blessed wherever I am and has enjoined upon me prayer and zakah."},
    {"num": 32, "ar": "وَبَرًّا بِوَالِدَتِي وَلَمْ يَجْعَلْنِي جَبَّارًا شَقِيًّا", "en": "And made me dutiful to my mother, and He has not made me a wretched tyrant."},
    {"num": 33, "ar": "وَالسَّلَامُ عَلَيَّ يَوْمَ وُلِدتُّ وَيَوْمَ أَمُوتُ وَيَوْمَ أُبْعَثُ حَيًّا", "en": "And peace is on me the day I was born and the day I will die and the day I am raised alive."},
]

MIRACLES = [
    {"icon": "1", "title": L("Speaking in the Cradle","Parler au berceau","Hablar en la cuna","Sprechen in der Wiege","Parlare nella culla","Falar no berco"),
     "text": L("As a newborn, Jesus spoke to defend his mother's honor: 'Indeed, I am the servant of Allah.'",
               "Nouveau-ne, Jesus parla pour defendre l'honneur de sa mere.",
               "Siendo recien nacido, Jesus hablo para defender el honor de su madre.",
               "Als Neugeborener sprach Jesus, um die Ehre seiner Mutter zu verteidigen.",
               "Appena nato, Gesu parlo per difendere l'onore di sua madre.",
               "Recem-nascido, Jesus falou para defender a honra de sua mae."),
     "ref": "Quran 19:29-33"},
    {"icon": "2", "title": L("Creating a Bird from Clay","Creer un oiseau d'argile","Crear un pajaro de barro","Einen Vogel aus Ton erschaffen","Creare un uccello dall'argilla","Criar um passaro de barro"),
     "text": L("By God's permission, Jesus shaped a bird from clay and breathed into it, and it became a living bird.",
               "Par la permission de Dieu, Jesus faconna un oiseau d'argile, et il devint vivant.",
               "Con el permiso de Dios, Jesus formo un pajaro de barro, y se convirtio en vivo.",
               "Mit Gottes Erlaubnis formte Jesus einen Vogel aus Ton, und er wurde lebendig.",
               "Con il permesso di Dio, Gesu plasmo un uccello dall'argilla, e divenne vivo.",
               "Com a permissao de Deus, Jesus moldou um passaro de barro, e se tornou vivo."),
     "ref": "Quran 3:49, 5:110"},
    {"icon": "3", "title": L("Healing the Blind and the Leper","Guerir l'aveugle et le lepreux","Sanar al ciego y al leproso","Heilung von Blinden und Aussatzigen","Guarire ciechi e lebbrosi","Curar cegos e leprosos"),
     "text": L("By God's permission, Jesus healed those born blind and those afflicted with leprosy.",
               "Par la permission de Dieu, Jesus guerit les aveugles de naissance et les lepreux.",
               "Con el permiso de Dios, Jesus sano a los ciegos y a los leprosos.",
               "Mit Gottes Erlaubnis heilte Jesus Blindgeborene und Aussatzige.",
               "Con il permesso di Dio, Gesu guari i ciechi e i lebbrosi.",
               "Com a permissao de Deus, Jesus curou cegos e leprosos."),
     "ref": "Quran 3:49, 5:110"},
    {"icon": "4", "title": L("Raising the Dead","Ressusciter les morts","Resucitar a los muertos","Tote auferwecken","Risuscitare i morti","Ressuscitar os mortos"),
     "text": L("By God's permission, Jesus raised the dead to life - a sign of God's power over life and death.",
               "Par la permission de Dieu, Jesus ressuscita les morts.",
               "Con el permiso de Dios, Jesus resucito a los muertos.",
               "Mit Gottes Erlaubnis erweckte Jesus Tote zum Leben.",
               "Con il permesso di Dio, Gesu risuscito i morti.",
               "Com a permissao de Deus, Jesus ressuscitou os mortos."),
     "ref": "Quran 3:49, 5:110"},
    {"icon": "5", "title": L("Knowing Hidden Things","Connaitre les choses cachees","Conocer las cosas ocultas","Verborgenes wissen","Conoscere le cose nascoste","Conhecer coisas ocultas"),
     "text": L("By God's permission, Jesus informed people of what they ate and what they stored.",
               "Par la permission de Dieu, Jesus informait les gens de ce qu'ils mangeaient.",
               "Con el permiso de Dios, Jesus informaba a la gente de lo que comian.",
               "Mit Gottes Erlaubnis teilte Jesus mit, was sie assen.",
               "Con il permesso di Dio, Gesu informava su cio che mangiavano.",
               "Com a permissao de Deus, Jesus informava sobre o que comiam."),
     "ref": "Quran 3:49"},
    {"icon": "6", "title": L("Born of a Virgin","Ne d'une vierge","Nacido de una virgen","Von einer Jungfrau geboren","Nato da una vergine","Nascido de uma virgem"),
     "text": L("The greatest miracle: Jesus was born without a father, by God's command Be - just as Adam was created without father or mother.",
               "Le plus grand miracle : Jesus naquit sans pere, par l'ordre de Dieu Sois.",
               "El mayor milagro: Jesus nacio sin padre, por orden de Dios Se.",
               "Das groesste Wunder: Jesus wurde ohne Vater geboren.",
               "Il piu grande miracolo: Gesu nacque senza padre.",
               "O maior milagre: Jesus nasceu sem pai."),
     "ref": "Quran 3:47, 19:20-21, 21:91"},
]

QUESTIONS = [
    {"q": L("Did Jesus claim to be God?","Jesus a-t-il pretendu etre Dieu ?","Jesus afirmo ser Dios?","Behauptete Jesus, Gott zu sein?","Gesu affermo di essere Dio?","Jesus afirmou ser Deus?"),
     "a": L("Nowhere in the Bible does Jesus say 'I am God, worship me.' He said: 'The Father is greater than I' (John 14:28). In the Quran: 'Allah is my Lord and your Lord.' (3:51)",
            "Nulle part Jesus ne dit 'Je suis Dieu.' Il dit : 'Le Pere est plus grand que moi' (Jean 14:28). Dans le Coran : 'Allah est mon Seigneur.' (3:51)",
            "En ninguna parte Jesus dice 'Soy Dios.' El dijo: 'El Padre es mayor que yo' (Juan 14:28). En el Coran: 'Allah es mi Senor.' (3:51)",
            "Nirgends sagt Jesus 'Ich bin Gott.' Er sagte: 'Der Vater ist groesser als ich' (Johannes 14:28). Im Koran: 'Allah ist mein Herr.' (3:51)",
            "In nessuna parte Gesu dice 'Sono Dio.' Disse: 'Il Padre e piu grande di me' (Giovanni 14:28). Nel Corano: 'Allah e il mio Signore.' (3:51)",
            "Em nenhum lugar Jesus diz 'Sou Deus.' Ele disse: 'O Pai e maior do que eu' (Joao 14:28). No Alcorao: 'Allah e meu Senhor.' (3:51)")},
    {"q": L("Why don't Muslims believe Jesus was crucified?","Pourquoi les musulmans ne croient-ils pas a la crucifixion ?","Por que los musulmanes no creen en la crucifixion?","Warum glauben Muslime nicht an die Kreuzigung?","Perche i musulmani non credono alla crocifissione?","Por que os muculmanos nao creem na crucificacao?"),
     "a": L("The Quran says: 'They did not kill him, nor did they crucify him; but another was made to resemble him... Rather, Allah raised him to Himself.' (4:157-158).",
            "Le Coran dit : 'Ils ne l'ont ni tue ni crucifie ; mais ce n'etait qu'un faux-semblant.' (4:157-158).",
            "El Coran dice: 'No lo mataron ni lo crucificaron, sino que les parecio asi.' (4:157-158).",
            "Der Koran sagt: 'Sie haben ihn weder getoetet noch gekreuzigt.' (4:157-158).",
            "Il Corano dice: 'Non lo uccisero ne lo crocifissero.' (4:157-158).",
            "O Alcorao diz: 'Nao o mataram nem o crucificaram.' (4:157-158).")},
    {"q": L("What about the Trinity?","Et la Trinite ?","Y la Trinidad?","Was ist mit der Dreieinigkeit?","E la Trinita?","E a Trindade?"),
     "a": L("The Quran says: 'O People of the Book, do not exceed the limits. The Messiah was only a messenger of Allah. And do not say, Three; desist.' (4:171)",
            "Le Coran dit : 'O gens du Livre, n'exagerez pas. Le Messie n'etait qu'un messager. Ne dites pas : Trois.' (4:171)",
            "El Coran dice: 'Oh gente del Libro, no exagereis. El Mesias era solo un mensajero. No digais: Tres.' (4:171)",
            "Der Koran sagt: 'O Leute der Schrift, uebertreibt nicht. Sagt nicht: Drei.' (4:171)",
            "Il Corano dice: 'O gente del Libro, non esagerate. Non dite: Tre.' (4:171)",
            "O Alcorao diz: 'O Povo do Livro, nao exagereis. Nao digais: Tres.' (4:171)")},
    {"q": L("Was Jesus a Muslim?","Jesus etait-il musulman ?","Era Jesus musulman?","War Jesus Muslim?","Gesu era musulmano?","Jesus era muculmano?"),
     "a": L("The word 'Muslim' means 'one who submits to God'. Jesus submitted completely to God and said: 'Not my will, but Yours be done' (Luke 22:42).",
            "Le mot 'musulman' signifie 'celui qui se soumet a Dieu'. Jesus se soumit et dit : 'Que ta volonte soit faite.' (Luc 22:42)",
            "La palabra 'musulman' significa 'el que se somete a Dios'. Jesus dijo: 'No se haga mi voluntad, sino la tuya.' (Lucas 22:42)",
            "Das Wort 'Muslim' bedeutet 'einer, der sich Gott hingibt'. Jesus sagte: 'Nicht mein Wille, sondern der Deine.' (Lukas 22:42)",
            "La parola 'musulmano' significa 'colui che si sottomette a Dio'. Gesu disse: 'Non la mia volonta, ma la tua.' (Luca 22:42)",
            "A palavra 'muculmano' significa 'aquele que se submete a Deus'. Jesus disse: 'Nao a minha vontade, mas a tua.' (Lucas 22:42)")},
    {"q": L("Did Jesus predict Muhammad?","Jesus a-t-il annonce Muhammad ?","Predijo Jesus a Muhammad?","Hat Jesus Muhammad vorhergesagt?","Gesu predisse Muhammad?","Jesus previu Muhammad?"),
     "a": L("Jesus said: 'I will ask the Father, and He will give you another Comforter' (John 14:16). The Quran says Jesus gave 'glad tidings of a messenger to come after me, whose name is Ahmad' (61:6).",
            "Jesus dit : 'Je prierai le Pere, et Il vous donnera un autre Consolateur.' (Jean 14:16). Le Coran dit : 'un messager dont le nom est Ahmad.' (61:6)",
            "Jesus dijo: 'Rogare al Padre, y El os dara otro Consolador' (Juan 14:16). El Coran dice: 'un mensajero cuyo nombre es Ahmad.' (61:6)",
            "Jesus sagte: 'Ich werde den Vater bitten, und Er wird euch einen anderen Troester geben' (Johannes 14:16). Der Koran: 'einen Gesandten, dessen Name Ahmad ist.' (61:6)",
            "Gesu disse: 'Io preghero il Padre, ed Egli vi dara un altro Consolatore' (Giovanni 14:16). Il Corano: 'un messaggero il cui nome e Ahmad.' (61:6)",
            "Jesus disse: 'Rogarei ao Pai, e Ele vos dara outro Consolador' (Joao 14:16). O Alcorao: 'um mensageiro cujo nome e Ahmad.' (61:6)")},
]

PROPHECIES = [
    {"source": "Deuteronomy 18:18",
     "text": L("'I will raise up for them a prophet like you from among their brothers.' - Moses spoke of a prophet from among the Ishmaelites.",
               "'Je leur susciterai du milieu de leurs freres un prophete comme toi.' - Moise parla des Ismaelites.",
               "'Profeta de entre sus hermanos levantare.' - Moises hablo de los ismaelitas.",
               "'Einen Propheten wie dich will ich aus der Mitte ihrer Brueder erwecken.' - Mose sprach von den Ismaeliten.",
               "'Un profeta come te suscitero tra i loro fratelli.' - Mose parlo degli ismaeliti.",
               "'Um profeta como tu levantarei dentre seus irmaos.' - Moises falou dos ismaelitas.")},
    {"source": "Isaiah 42:11",
     "text": L("'Let the wilderness and its cities lift up their voice, the villages that Kedar inhabits.' - Kedar is the son of Ishmael.",
               "'Que le desert et ses villes elevent la voix, les villages qu'habite Kedar.' - Kedar est fils d'Ismael.",
               "'Alcen la voz el desierto y sus ciudades, las aldeas donde habita Cedar.' - Cedar es hijo de Ismael.",
               "'Die Wueste und ihre Staedte sollen ihre Stimme erheben.' - Kedar ist Ismaels Sohn.",
               "'Il deserto e le sue citta alzino la voce.' - Kedar e figlio di Ismaele.",
               "'O deserto e suas cidades levantem a voz.' - Quedar e filho de Ismael.")},
    {"source": "John 16:12-13",
     "text": L("'I have yet many things to say unto you, but ye cannot bear them now. When he, the Spirit of truth, is come, he will guide you into all truth.'",
               "'J'ai encore beaucoup de choses a vous dire. Quand le Consolateur sera venu, il vous conduira dans toute la verite.'",
               "'Aun tengo muchas cosas que deciros. Cuando venga el Consolador, el os guiara a toda la verdad.'",
               "'Ich habe euch noch viel zu sagen. Wenn der Geist der Wahrheit kommen wird, wird er euch leiten.'",
               "'Ho ancora molte cose da dirvi. Quando verra il Consolatore, vi guidera alla verita.'",
               "'Ainda tenho muito que vos dizer. Quando vier o Consolador, ele vos guiara a toda a verdade.'")},
    {"source": "John 14:16",
     "text": L("'I will pray the Father, and he shall give you another Comforter, that he may abide with you for ever.' - Muslims believe this is Muhammad, whose law abides forever.",
               "'Je prierai le Pere, et Il vous donnera un autre Consolateur, afin qu'il demeure eternellement avec vous.' - Les musulmans croient que c'est Muhammad.",
               "'Y yo rogare al Padre, y os dara otro Consolador, para que este con vosotros para siempre.' - Los musulmanes creen que es Muhammad.",
               "'Ich will den Vater bitten, und er wird euch einen anderen Troester geben.' - Muslime glauben, dies ist Muhammad.",
               "'Io preghero il Padre, ed Egli vi dara un altro Consolatore.' - I musulmani credono sia Muhammad.",
               "'E eu rogarei ao Pai, e Ele vos dara outro Consolador.' - Muculmanos creem que e Muhammad.")},
    {"source": "Song of Solomon 5:16",
     "text": L("'His mouth is most sweet: yea, he is altogether lovely.' - In Hebrew: 'Machamaddim' - the plural of 'Muhammad'.",
               "'Sa bouche est toute douceur, et toute sa personne est desirable.' - En hebreu : 'Machamaddim' - pluriel de 'Muhammad'.",
               "'Su paladar es dulcisimo, y todo el es deseable.' - En hebreo: 'Machamaddim' - plural de 'Muhammad'.",
               "'Sein Mund ist suess, und alles an ihm ist lieblich.' - Im Hebraeischen: 'Machamaddim'.",
               "'Il suo palato e dolcissimo, tutto in lui e delizioso.' - In ebraico: 'Machamaddim'.",
               "'A sua boca e muitissimo suave, ele e totalmente desejavel.' - Em hebraico: 'Machamaddim'.")},
]
