# -*- coding: utf-8 -*-

# Hindi + English content (romanized Hindi for readability)
def H(hi, en):
    return {"hi": hi, "en": en}

INTRO_HI = H(
 "Namaste. Hum aapka ehtram karte hain. Hum aapko Islam ki taraf bulate hain - tark aur dil ke zariye, kisi zabardasti ke baghair. Aapke mazhab mein sach ki talash hai - hum sirf aapko ek sawal pesh karte hain: kya patthar, gaay, ya sooraj aapka Khaliq ho sakta hai?",
 "Namaste. We respect you. We invite you to Islam - through reason and heart, without any compulsion. Your faith has a search for truth - we simply present you with one question: can a stone, a cow, or the sun be your Creator?",
)

# 10 Questions for Hindus to think about
QUESTIONS_HINDU = [
    {
        "num": 1,
        "title": H("Kya Patthar Khaliq Ho Sakta Hai?",
                   "Can a Stone Be a Creator?"),
        "text": H("Aap ek murti ki pooja karte hain. Lekin woh murti kis ne banayi? Ek murti jo khud banayi gayi ho, khud toot sakti ho, khud mitti mein mil jaye - kya woh aapko paida kar sakti hai? Aap khud murti banate hain, phir usi ke saamne sajda karte hain. Yeh kaisa Khaliq hai?",
                  "You worship an idol. But who made that idol? An idol that was made, that can break, that will turn to dust - can it create you? You make the idol yourself, then bow to it. What kind of Creator is this?"),
        "verse_ar": "أَتَعْبُدُونَ مَا تَنْحِتُونَ",
        "verse_en": "Do you worship what you carve?",
        "ref": "Quran 37:95",
    },
    {
        "num": 2,
        "title": H("Gaay Ke Baare Mein Sawal",
                   "The Question About the Cow"),
        "text": H("Aap gaay ki pooja karte hain. Lekin gaay khud ghaas khaati hai, paani peeti hai, gobar karti hai. Woh khud kisi ki mohtaaj hai. Jo khud mohtaaj ho, woh khuda kaise ho sakta hai? Khuda ko khane, peene, sone ki zarurat nahi hoti.",
                  "You worship the cow. But the cow eats grass, drinks water, and produces dung. She herself is dependent on others. How can the dependent be God? God has no need to eat, drink, or sleep."),
        "verse_ar": "وَاللَّهُ الْغَنِيُّ وَأَنتُمُ الْفُقَرَاءُ",
        "verse_en": "And Allah is the Free of need, while you are the needy.",
        "ref": "Quran 47:38",
    },
    {
        "num": 3,
        "title": H("Sooraj Aur Chaand Ka Sawal",
                   "The Question About the Sun and Moon"),
        "text": H("Aap sooraj ko pooja karte hain. Lekin sooraj roz doobta hai. Raat ko sooraj kahan jaata hai? Agar sooraj khuda hota, woh roz chhupta kyun? Jo chhup jaye, woh kabhi Khaliq nahi ho sakta. Khuda woh hai jo kabhi nahi chhupta.",
                  "You worship the sun. But the sun sets every day. Where does the sun go at night? If the sun were God, why does it hide daily? What hides can never be the Creator. God is the One who never hides."),
        "verse_ar": "لَا الشَّمْسُ يَنبَغِي لَهَا أَن تُدْرِكَ الْقَمَرَ",
        "verse_en": "It is not for the sun to overtake the moon, nor does the night outstrip the day.",
        "ref": "Quran 36:40",
    },
    {
        "num": 4,
        "title": H("Kitne Khuda?",
                   "How Many Gods?"),
        "text": H("Hindu dharam mein kaha jaata hai ke 33 crore devta hain. Sochiye - agar 33 crore khuda hote, duniya mein kitna bura hota? Har khuda apni marzi chalata, sab ladte. Lekin aap dekh rahe hain - sooraj, chaand, taare, sab ek perfect order mein hain. Yeh ek Allah ka kaam hai.",
                  "In Hindu dharma it is said there are 330 million gods. Think - if there were 330 million gods, how chaotic the world would be? Each would impose his will, all would fight. But you see - sun, moon, stars - all in perfect order. This is the work of One Allah."),
        "verse_ar": "لَوْ كَانَ فِيهِمَا آلِهَةٌ إِلَّا اللَّهُ لَفَسَدَتَا",
        "verse_en": "If there were in the heavens and earth gods besides Allah, they would have fallen into ruin.",
        "ref": "Quran 21:22",
    },
    {
        "num": 5,
        "title": H("Aap Khud Khuda Nahi - Magar Aap Khuda Ke Banday Ho",
                   "You Are Not God - But You Are God's Servant"),
        "text": H("Aap sochiye - aap paida kaise huay? Aapke maa-baap ne aapko paida kiya. Unko unke maa-baap ne. Yeh silsila chalta raha. Har cheez jo paida hui, uska ek Khaliq hai. Sirf Allah hi woh hai jo nahi paida hua - woh hamesha se hai.",
                  "Think - how were you born? Your parents gave you birth. They were born to their parents. The chain continues. Everything that was born has a Creator. Only Allah is the One who was never born - He always is."),
        "verse_ar": "لَمْ يَلِدْ وَلَمْ يُولَدْ",
        "verse_en": "He neither begets nor is born.",
        "ref": "Quran 112:3",
    },
    {
        "num": 6,
        "title": H("Ganga Nadi Ka Sawal",
                   "The Question About the Ganges"),
        "text": H("Aap Ganga ko pavitra kehte hain. Lekin Ganga ek nadi hai - paani. Paani khud paani hai, woh paap kaise mita sakti hai? Paap woh dhabba nahi jo paani se dhul jaye. Paap dil ka hai - uska ilaaj sirf Allah ki taraf laut kar, usse maafi maangne se hota hai.",
                  "You call the Ganges holy. But the Ganges is a river - water. Water is itself water, how can it erase sin? Sin is not a stain that water can wash. Sin is of the heart - its cure is only by returning to Allah and seeking His forgiveness."),
        "verse_ar": "إِنَّ اللَّهَ يُحِبُّ التَّوَّابِينَ وَيُحِبُّ الْمُتَطَهِّرِينَ",
        "verse_en": "Indeed, Allah loves those who repent and loves those who purify themselves.",
        "ref": "Quran 2:222",
    },
    {
        "num": 7,
        "title": H("Karma Aur Reenkarnasyon",
                   "Karma and Reincarnation"),
        "text": H("Aap karma aur punarjanm mein vishwas karte hain. Lekin punarjanm ka koi gawah kisi ne nahi dekha. Kya aapko yaad hai aap pehle kya the? Agar aapko apna pichhla janam yaad nahi, toh agla janam kaise jaanoge? Islam kehta hai - ek zindagi, ek maut, phir hisaab. Yeh zyada adl hai.",
                  "You believe in karma and reincarnation. But no one has ever witnessed reincarnation. Do you remember what you were before? If you don't remember your last birth, how will you know the next? Islam says - one life, one death, then accountability. This is more just."),
        "verse_ar": "حَتَّىٰ إِذَا جَاءَ أَحَدَهُمُ الْمَوْتُ قَالَ رَبِّ ارْجِعُونِ",
        "verse_en": "Until, when death comes to one of them, he says: My Lord, send me back.",
        "ref": "Quran 23:99",
    },
    {
        "num": 8,
        "title": H("Antim Kitab - Quran",
                   "The Final Book - The Quran"),
        "text": H("Ved, Puran, Geeta - sab kitabein hain. Lekin in mein insani haath ne badlav kiya. Kuch hisse jod diye, kuch hata diye. Sirf Quran hi woh kitab hai jo 1400 saal se bilkul waisi hai jaisi utri. Ek hi lafz bhi nahi badla. Yeh khud ek sabut hai ke Quran Allah ki kitab hai.",
                  "Vedas, Puranas, Gita - all are books. But human hands changed them. Some parts added, some removed. Only the Quran is the book that for 1400 years remains exactly as it was revealed. Not one word changed. This itself is proof that the Quran is the Book of Allah."),
        "verse_ar": "إِنَّا نَحْنُ نَزَّلْنَا الذِّكْرَ وَإِنَّا لَهُ لَحَافِظُونَ",
        "verse_en": "Indeed, it is We who sent down the Quran, and indeed, We will be its Guardian.",
        "ref": "Quran 15:9",
    },
    {
        "num": 9,
        "title": H("Aap Islam Kyun Qubool Karein?",
                   "Why Should You Accept Islam?"),
        "text": H("Islam aapko deta hai: (1) Ek Allah, koi shirk nahi. (2) Paigham-e-Aman. (3) Aurat ko izzat. (4) Ghulami se azadi. (5) Maut ke baad insaf. (6) Jannat ki khushkhabri. Aap kuch nahi kho rahe - aap sirf apni rooh ko uski asal jagah laa rahe ho.",
                  "Islam gives you: (1) One Allah, no shirk. (2) A message of peace. (3) Honor for women. (4) Freedom from slavery. (5) Justice after death. (6) Glad tidings of Paradise. You lose nothing - you only return your soul to its origin."),
        "verse_ar": "لَا إِكْرَاهَ فِي الدِّينِ ۖ قَد تَّبَيَّنَ الرُّشْدُ مِنَ الْغَيِّ",
        "verse_en": "There is no compulsion in religion. The right course has become clear from the wrong.",
        "ref": "Quran 2:256",
    },
    {
        "num": 10,
        "title": H("Ek Seedha Dua",
                   "A Simple Prayer"),
        "text": H("Agar aap sach ke talash mein ho, toh dil se kahein: 'Aye Khaliq - agar tum ho, toh mujhe hidayat de.' Yeh dua Allah zarur sunta hai. Bahut Hindu bhaiyon ne yeh dua ki, aur unhe sach mil gaya. Woh aaj duniya ke 2 billion Musalmano mein se ek hain - aur unki zindagi badal gayi.",
                  "If you are searching for the truth, say sincerely: 'O Creator - if You exist, guide me.' Allah surely hears this prayer. Many Hindu brothers made this prayer, and they found the truth. They are today among the 2 billion Muslims - and their lives were transformed."),
        "verse_ar": "وَالَّذِينَ جَاهَدُوا فِينَا لَنَهْدِيَنَّهُمْ سُبُلَنَا",
        "verse_en": "And those who strive for Us - We will surely guide them to Our ways.",
        "ref": "Quran 29:69",
    },
]

# Comparison chart: Hinduism vs Islam
COMPARISON_HI = [
    {"topic": H("Khuda", "God"),
     "hindu": H("33 crore devta", "330 million gods"),
     "islam": H("Ek Allah - La Shareek Lah", "One Allah - no partner")},
    {"topic": H("Murti Pooja", "Idol Worship"),
     "hindu": H("Patthar, mitti, dhaatu ki murti", "Idols of stone, clay, metal"),
     "islam": H("Sirf Allah ki ibadat", "Worship of Allah alone")},
    {"topic": H("Avtar", "Avatars"),
     "hindu": H("Ram, Krishna, etc.", "Ram, Krishna, etc."),
     "islam": H("Nabi aur Rasool - insan, khuda nahi", "Prophets and Messengers - humans, not gods")},
    {"topic": H("Gaay", "Cow"),
     "hindu": H("Pavitra, poojya", "Holy, worshipped"),
     "islam": H("Allah ki makhlooq - khane ke liye halal", "A creation of Allah - lawful to eat")},
    {"topic": H("Maut Ke Baad", "After Death"),
     "hindu": H("Punarjanm - anant chakra", "Reincarnation - endless cycle"),
     "islam": H("Ek zindagi, phir hisaab", "One life, then accountability")},
    {"topic": H("Kitab", "Book"),
     "hindu": H("Ved, Puran, Geeta (badle hue)", "Vedas, Puranas, Gita (changed)"),
     "islam": H("Quran (mahfooz)", "Quran (preserved)")},
    {"topic": H("Aurat", "Women"),
     "hindu": H("Kabhi devi, kabhi dasi", "Sometimes goddess, sometimes servant"),
     "islam": H("Izzat, huqooq, virasat", "Honor, rights, inheritance")},
    {"topic": H("Caste", "Caste System"),
     "hindu": H("Chaar varna - janm se", "Four castes - by birth"),
     "islam": H("Sab barabar - sirf taqwa se farq", "All equal - only piety distinguishes")},
]
