# -*- coding: utf-8 -*-

def L(en, fr, es, de, it, pt):
    return {"en": en, "fr": fr, "es": es, "de": de, "it": it, "pt": pt}

INTRO = L(
 "Before Islam, in 7th-century Arabia, baby girls were sometimes buried alive. Women had no right to inherit, no right to own property, no right to choose a husband. Islam came and abolished these practices. The Prophet said: 'The best of you is the best to his wife.' The Quran honored women as mothers, daughters, wives, and believers with their own rights and dignity.",
 "Avant l'Islam, en Arabie du 7e siecle, les filles etaient parfois enterrees vivantes. Les femmes n'avaient aucun droit d'heriter ni de choisir un mari. L'Islam est venu abolir ces pratiques.",
 "Antes del Islam, en Arabia del siglo VII, las ninas a veces eran enterradas vivas. Las mujeres no tenian derecho a heredar ni a elegir marido. El Islam aboli estas practicas.",
 "Vor dem Islam wurden im Arabien des 7. Jahrhunderts Maedchen lebendig begraben. Frauen hatten kein Erb- oder Wahlrecht. Der Islam schaffte diese Praktiken ab.",
 "Prima dell'Islam, nell'Arabia del VII secolo, le bambine venivano a volte sepolte vive. Le donne non avevano diritti. L'Islam abolì queste pratiche.",
 "Antes do Isla, na Arabia do seculo VII, meninas eram enterradas vivas. As mulheres nao tinham direitos. O Isla aboliu essas praticas.",
)

# ============ MISCONCEPTIONS ============
MISCONCEPTIONS = [
    {
        "num": 1,
        "title": L("The Hijab","Le Hijab","El Hiyab","Das Kopftuch","L'Hijab","O Hijab"),
        "misc": L("The hijab oppresses women and silences them.",
                  "Le hijab opprime les femmes et les reduit au silence.",
                  "El hiyab oprime a las mujeres y las silencia.",
                  "Das Kopftuch unterdrueckt Frauen und macht sie stumm.",
                  "L'hijab opprime le donne e le riduce al silenzio.",
                  "O hijab oprime as mulheres e as silencia."),
        "answer": L("The hijab is not oppression. It is dignity, modesty, and a woman's own choice. Islam forbids forcing it: 'There is no compulsion in religion' (Quran 2:256). Many Western women who embraced Islam say: 'The hijab freed me from being judged by my body.'",
                    "Le hijab n'est pas une oppression. C'est la dignite et le choix de la femme. L'Islam interdit de forcer : 'Nulle contrainte en religion' (2:256).",
                    "El hiyab no es opresion. Es dignidad y eleccion. El Islam prohibe forzarlo: 'No hay coaccion en religion' (2:256).",
                    "Das Kopftuch ist keine Unterdrueckung. Es ist Wuerde und Wahl. Der Islam verbietet Zwang: 'Kein Zwang im Glauben' (2:256).",
                    "L'hijab non e oppressione. E dignita e scelta. L'Islam vieta la costrizione: 'Nessuna costrizione nella religione' (2:256).",
                    "O hijab nao e opressao. E dignidade e escolha. O Isla proibe forcar: 'Nao ha compulsao na religiao' (2:256)."),
        "ref": "Quran 2:256, 24:31",
    },
    {
        "num": 2,
        "title": L("Polygamy","La Polygamie","La Poligamia","Polygamie","La Poligamia","A Poligamia"),
        "misc": L("Islam invented polygamy and allows men to marry many women.",
                  "L'Islam a invente la polygamie et permet aux hommes d'epouser plusieurs femmes.",
                  "El Islam invento la poligamia y permite a los hombres casarse con muchas mujeres.",
                  "Der Islam hat die Polygamie erfunden.",
                  "L'Islam ha inventato la poligamia.",
                  "O Isla inventou a poligamia."),
        "answer": L("Islam did not invent polygamy - it restricted it. Before Islam, Arab men could marry unlimited women. The Quran limited it to four with strict conditions of justice, and said: 'If you fear you will not be just, then marry only one' (4:3). Most Muslim men today have one wife.",
                    "L'Islam n'a pas invente la polygamie - il l'a restreinte a quatre, avec des conditions strictes. 'Si vous craignez de ne pas etre justes, epousez une seule.' (4:3)",
                    "El Islam no invento la poligamia - la restringio a cuatro con condiciones. 'Si temeis no ser justos, casaos con una sola.' (4:3)",
                    "Der Islam hat die Polygamie nicht erfunden - er beschraenkte sie auf vier. 'Wenn ihr fuerchtet, nicht gerecht zu sein, dann heiratet nur eine.' (4:3)",
                    "L'Islam non ha inventato la poligamia - la limito a quattro. 'Se temete di non essere giusti, sposate una sola.' (4:3)",
                    "O Isla nao inventou a poligamia - limitou-a a quatro. 'Se temeis nao ser justos, casai-vos com apenas uma.' (4:3)"),
        "ref": "Quran 4:3, 4:129",
    },
    {
        "num": 3,
        "title": L("Inheritance","L'Heritage","La Herencia","Erbschaft","L'Eredità","A Herança"),
        "misc": L("Women get half of what men get. That is unfair.",
                  "Les femmes recoivent la moitie de ce que les hommes recoivent. C'est injuste.",
                  "Las mujeres reciben la mitad que los hombres. Eso es injusto.",
                  "Frauen bekommen die Haelfte von dem, was Maenner bekommen. Das ist unfair.",
                  "Le donne ricevono la meta di cio che ricevono gli uomini. Ingiusto.",
                  "As mulheres recebem metade do que os homens recebem. Injusto."),
        "answer": L("Yes, in some cases a woman's share is half. But consider: a woman keeps 100% of her own wealth. A man must spend his wealth on his wife, children, and parents. The woman's share is hers to keep - the man's is a responsibility.",
                    "Oui, parfois la part de la femme est la moitie. Mais la femme garde 100% de sa richesse. L'homme doit depenser pour sa femme, ses enfants et ses parents.",
                    "Si, a veces la parte de la mujer es la mitad. Pero ella conserva el 100%. El hombre debe gastar en su esposa, hijos y padres.",
                    "Ja, manchmal ist der Anteil der Frau die Haelfte. Aber sie behaelt 100% ihres Vermoegens. Der Mann muss fuer Familie sorgen.",
                    "Si, a volte la quota della donna e la meta. Ma lei conserva il 100%. L'uomo deve spendere per la famiglia.",
                    "Sim, as vezes a parte da mulher e metade. Mas ela mantem 100%. O homem deve gastar com a familia."),
        "ref": "Quran 4:7, 4:11",
    },
    {
        "num": 4,
        "title": L("Testimony","Le Témoignage","El Testimonio","Zeugnis","La Testimonianza","O Testemunho"),
        "misc": L("A woman's testimony is worth half of a man's.",
                  "Le temoignage d'une femme vaut la moitie de celui d'un homme.",
                  "El testimonio de una mujer vale la mitad del de un hombre.",
                  "Das Zeugnis einer Frau ist die Haelfte wert.",
                  "La testimonianza di una donna vale la meta di quella di un uomo.",
                  "O testemunho de uma mulher vale metade do de um homem."),
        "answer": L("In financial contracts only, two women replace one man - because at that time women generally did not deal with finances, and Islam wanted to protect her from pressure. In all other legal matters, a woman's testimony equals a man's, and can even override it.",
                    "Dans les contrats financiers uniquement, deux femmes remplacent un homme - pour proteger la femme. Dans tous les autres domaines, son temoignage egale celui de l'homme.",
                    "Solo en contratos financieros, dos mujeres reemplazan a un hombre - para protegerla. En todos los demas, su testimonio es igual al del hombre.",
                    "Nur bei Finanzvertraegen ersetzen zwei Frauen einen Mann - zum Schutz der Frau. In allen anderen Faellen ist ihr Zeugnis gleichwertig.",
                    "Solo nei contratti finanziari, due donne sostituiscono un uomo - per proteggerla. In tutti gli altri casi, il suo testimonio e pari.",
                    "Apenas em contratos financeiros, duas mulheres substituem um homem - para protege-la. Em todos os outros casos, seu testemunho e igual."),
        "ref": "Quran 2:282",
    },
    {
        "num": 5,
        "title": L("Marriage & Consent","Le Mariage et le Consentement","El Matrimonio y el Consentimiento","Ehe und Zustimmung","Matrimonio e Consenso","Casamento e Consentimento"),
        "misc": L("Muslim women are forced into marriages.",
                  "Les femmes musulmanes sont forcees au mariage.",
                  "Las mujeres musulmanas son forzadas al matrimonio.",
                  "Muslimische Frauen werden zur Ehe gezwungen.",
                  "Le donne musulmane sono costrette al matrimonio.",
                  "As mulheres muculmanas sao forcadas ao casamento."),
        "answer": L("Islam requires a woman's free consent for marriage. Forced marriage is invalid. The Prophet said: 'A virgin must not be married until her permission is sought.' She keeps her own name, her own wealth, and her own property after marriage.",
                    "L'Islam exige le consentement libre de la femme. Le mariage force est invalide. 'Une vierge ne doit pas etre mariee sans son consentement.'",
                    "El Islam exige el consentimiento libre. El matrimonio forzado es invalido. 'Una virgen no debe ser casada sin su permiso.'",
                    "Der Islam verlangt die freie Zustimmung der Frau. Zwangsehen sind ungueltig. 'Eine Jungfrau darf nicht ohne ihre Zustimmung verheiratet werden.'",
                    "L'Islam richiede il consenso libero. Il matrimonio forzato e invalido. 'Una vergine non deve essere sposata senza il suo consenso.'",
                    "O Isla exige o consentimento livre. O casamento forcado e invalido. 'Uma virgem nao deve ser casada sem seu consentimento.'"),
        "ref": "Sahih Bukhari, Sahih Muslim",
    },
    {
        "num": 6,
        "title": L("Education & Work","L'Education et le Travail","La Educacion y el Trabajo","Bildung und Arbeit","Istruzione e Lavoro","Educacao e Trabalho"),
        "misc": L("Women in Islam are forbidden from education and work.",
                  "Les femmes en Islam sont interdites d'education et de travail.",
                  "Las mujeres en el Islam tienen prohibida la educacion y el trabajo.",
                  "Frauen im Islam ist Bildung und Arbeit verboten.",
                  "Le donne nell'Islam sono escluse da istruzione e lavoro.",
                  "Mulheres no Isla sao proibidas de educacao e trabalho."),
        "answer": L("The Prophet said: 'Seeking knowledge is an obligation upon every Muslim' - male and female. Khadija was a successful businesswoman. Aisha was a scholar who taught men. Muslim women today are doctors, engineers, professors, and heads of state.",
                    "Le Prophete a dit : 'La recherche du savoir est une obligation pour chaque musulman.' Khadija etait une femme d'affaires. Aisha enseignait aux hommes.",
                    "El Profeta dijo: 'Buscar conocimiento es obligacion de todo musulman.' Jadiya era empresaria. Aisha ensenaba a hombres.",
                    "Der Prophet sagte: 'Wissenssuche ist Pflicht jedes Muslims.' Khadija war Geschaeftsfrau. Aisha lehrte Maenner.",
                    "Il Profeta disse: 'Cercare il sapere e obbligo di ogni musulmano.' Khadija era imprenditrice. Aisha insegnava agli uomini.",
                    "O Profeta disse: 'Buscar conhecimento e obrigacao de todo muculmano.' Khadija era empresaria. Aisha ensinava homens."),
        "ref": "Ibn Majah, Sahih Bukhari",
    },
]

# ============ STORIES ============
STORIES = [
    {
        "icon": "K",
        "name": L("Khadija bint Khuwaylid","Khadija bint Khuwaylid","Jadiya bint Juwaylid","Khadija bint Khuwaylid","Khadija bint Khuwaylid","Khadija bint Khuwaylid"),
        "role": L("The First Believer, the Prophet's Wife","La Premiere Croyante","La Primera Creyente","Die erste Glaeubige","La Prima Credente","A Primeira Crente"),
        "text": L("A wealthy, respected businesswoman of Mecca. She employed Muhammad before marriage, then proposed to him. She was the first to believe in his message and supported him for 25 years. The Prophet said: 'She believed in me when no one else did.'",
                  "Une femme d'affaires riche et respectee de La Mecque. Elle l'employa avant le mariage. Elle fut la premiere a croire en son message et le soutint 25 ans.",
                  "Una empresaria rica y respetada de La Meca. Lo empleo antes del matrimonio. Fue la primera en creer y lo apoyo 25 anos.",
                  "Eine reiche Geschaeftsfrau in Mekka. Sie beschaeftigte ihn und war die erste Glaeubige. Sie unterstuetzte ihn 25 Jahre lang.",
                  "Una ricca imprenditrice della Mecca. Lo impiego prima del matrimonio. Fu la prima a credere e lo sostenne per 25 anni.",
                  "Uma empresaria rica de Meca. Empregou-o antes do casamento. Foi a primeira a crer e o apoiou por 25 anos."),
    },
    {
        "icon": "A",
        "name": L("Aisha bint Abi Bakr","Aisha bint Abi Bakr","Aisha bint Abi Bakr","Aisha bint Abi Bakr","Aisha bint Abi Bakr","Aisha bint Abi Bakr"),
        "role": L("The Scholar of the Ummah","La Savante de la Oumma","La Sabia de la Umma","Die Gelehrte der Umma","La Sapiente della Umma","A Sabia da Umma"),
        "text": L("A scholar of hadith, jurisprudence, and medicine. She narrated over 2,000 hadiths and taught thousands of men. When she differed with senior companions on legal issues, they consulted her. She is one of the greatest scholars in Islamic history.",
                  "Une savante du hadith, de la jurisprudence et de la medecine. Elle rapporta plus de 2 000 hadiths et enseigna a des milliers d'hommes.",
                  "Una sabia del hadiz, la jurisprudencia y la medicina. Narro mas de 2.000 hadices y enseno a miles de hombres.",
                  "Eine Gelehrte des Hadith, der Rechtswissenschaft und der Medizin. Sie ueberlieferte ueber 2.000 Hadithe.",
                  "Una sapiente del hadith, della giurisprudenza e della medicina. Narrò oltre 2.000 hadith.",
                  "Uma sabia do hadith, da jurisprudencia e da medicina. Narrou mais de 2.000 hadices."),
    },
    {
        "icon": "F",
        "name": L("Fatima al-Zahra","Fatima al-Zahra","Fatima al-Zahra","Fatima al-Zahra","Fatima al-Zahra","Fatima al-Zahra"),
        "role": L("The Prophet's Daughter","La Fille du Prophete","La Hija del Profeta","Die Tochter des Propheten","La Figlia del Profeta","A Filha do Profeta"),
        "text": L("A model of piety, patience, and strength. She stood by her father during the persecution in Mecca, comforted him after her mother's death, and was known for her deep worship and care for the poor. The Prophet said: 'Fatima is a part of me.'",
                  "Un modele de piete et de force. Elle soutint son pere pendant la persecution et etait connue pour son culte profond.",
                  "Un modelo de piedad y fuerza. Apoyo a su padre durante la persecucion y era conocida por su adoracion profunda.",
                  "Ein Vorbild an Froemmigkeit und Staerke. Sie stand ihrem Vater bei und war fuer ihre tiefe Anbetung bekannt.",
                  "Un modello di pieta e forza. Sostenne suo padre e era nota per la sua profonda adorazione.",
                  "Um modelo de piedade e forca. Apoiou seu pai e era conhecida por sua profunda adoracao."),
    },
]

# ============ WESTERN TESTIMONIES ============
TESTIMONIES = [
    {
        "name": "Yvonne Ridley",
        "country": L("United Kingdom","Royaume-Uni","Reino Unido","Vereinigtes Koenigreich","Regno Unito","Reino Unido"),
        "quote": L("I was captured by the Taliban - and I ended up embracing Islam. The hijab is not a sign of oppression - it is a sign of liberation.",
                   "J'ai ete capturee par les Talibans - et j'ai fini par embrasser l'Islam. Le hijab n'est pas un signe d'oppression - c'est un signe de liberation.",
                   "Fui capturada por los talibanes - y termine abrazando el Islam. El hiyab no es opresion - es liberacion.",
                   "Ich wurde von den Taliban gefangen genommen - und trat zum Islam ueber. Das Kopftuch ist ein Zeichen der Befreiung.",
                   "Fui catturata dai talebani - e finii per abbracciare l'Islam. L'hijab e un segno di liberazione.",
                   "Fui capturada pelo Taliba - e acabei abracando o Isla. O hijab e um sinal de libertacao."),
    },
    {
        "name": "Maryam Jameelah",
        "country": L("United States","Etats-Unis","Estados Unidos","Vereinigte Staaten","Stati Uniti","Estados Unidos"),
        "quote": L("Islam gave me a coherent worldview - a purpose for existence, a moral compass, and peace. I found what feminism promised but never delivered.",
                   "L'Islam m'a donne une vision coherente du monde - un but, une boussole morale et la paix. J'ai trouve ce que le feminisme promettait sans le donner.",
                   "El Islam me dio una vision coherente - un proposito, una brujula moral y paz. Encontre lo que el feminismo prometia pero no daba.",
                   "Der Islam gab mir ein kohaerentes Weltbild - einen Zweck, einen moralischen Kompass und Frieden.",
                   "L'Islam mi ha dato una visione coerente - uno scopo, una bussola morale e pace.",
                   "O Isla me deu uma visao coerente - um proposito, uma bussola moral e paz."),
    },
    {
        "name": "Aisha (formerly Teresa)",
        "country": L("Spain","Espagne","Espana","Spanien","Spagna","Espanha"),
        "quote": L("I found in Islam what feminism promised but never delivered - true respect. Islam honored me as a woman, as a mother, and as a believer.",
                   "J'ai trouve dans l'Islam ce que le feminisme promettait sans le donner - le vrai respect. L'Islam m'a honoree comme femme et mere.",
                   "Encontre en el Islam lo que el feminismo prometia - el verdadero respeto. El Islam me honro como mujer y madre.",
                   "Ich fand im Islam, was der Feminismus versprach - wahren Respekt. Der Islam ehrte mich als Frau und Mutter.",
                   "Ho trovato nell'Islam cio che il femminismo prometteva - il vero rispetto.",
                   "Encontrei no Isla o que o feminismo prometia - o verdadeiro respeito."),
    },
]

# ============ RIGHTS ============
RIGHTS = [
    L("Right to inherit","Droit d'heriter","Derecho a heredar","Recht zu erben","Diritto di ereditare","Direito de herdar"),
    L("Right to own property","Droit de posseder","Derecho a poseer","Recht auf Eigentum","Diritto di possedere","Direito de possuir"),
    L("Right to work","Droit de travailler","Derecho a trabajar","Recht zu arbeiten","Diritto di lavorare","Direito de trabalhar"),
    L("Right to education","Droit a l'education","Derecho a la educacion","Recht auf Bildung","Diritto all'istruzione","Direito a educacao"),
    L("Right to choose her husband","Droit de choisir son mari","Derecho a elegir marido","Recht, den Ehemann zu waehlen","Diritto di scegliere il marito","Direito de escolher o marido"),
    L("Right to keep her wealth","Droit de garder sa richesse","Derecho a conservar sus bienes","Recht, Vermoegen zu behalten","Diritto di conservare i beni","Direito de manter sua riqueza"),
    L("Right to seek divorce","Droit de demander le divorce","Derecho a pedir divorcio","Recht auf Scheidung","Diritto di chiedere il divorzio","Direito de pedir divorcio"),
    L("Right to be protected from harm","Droit d'etre protegee","Derecho a ser protegida","Recht auf Schutz","Diritto di essere protetta","Direito de ser protegida"),
]

# ============ QURANIC VERSES ============
VERSES = [
    {"ar": "وَمَن يَعْمَلْ مِنَ الصَّالِحَاتِ مِن ذَكَرٍ أَوْ أُنثَىٰ وَهُوَ مُؤْمِنٌ فَأُولَٰئِكَ يَدْخُلُونَ الْجَنَّةَ",
     "en": "And whoever does righteous deeds, whether male or female, while being a believer - those will enter Paradise.",
     "ref": "Quran 4:124"},
    {"ar": "هُنَّ لِبَاسٌ لَّكُمْ وَأَنتُمْ لِبَاسٌ لَّهُنَّ",
     "en": "They are clothing for you and you are clothing for them.",
     "ref": "Quran 2:187"},
    {"ar": "وَلَهُنَّ مِثْلُ الَّذِي عَلَيْهِنَّ بِالْمَعْرُوفِ",
     "en": "And women have rights similar to those over them, in fairness.",
     "ref": "Quran 2:228"},
    {"ar": "وَعَاشِرُوهُنَّ بِالْمَعْرُوفِ",
     "en": "And live with them in kindness.",
     "ref": "Quran 4:19"},
    {"ar": "وَالْمُؤْمِنُونَ وَالْمُؤْمِنَاتُ بَعْضُهُمْ أَوْلِيَاءُ بَعْضٍ",
     "en": "The believing men and believing women are allies of one another.",
     "ref": "Quran 9:71"},
    {"ar": "إِنَّ الْمُسْلِمِينَ وَالْمُسْلِمَاتِ وَالْمُؤْمِنِينَ وَالْمُؤْمِنَاتِ",
     "en": "Indeed, the Muslim men and Muslim women, the believing men and believing women - Allah has prepared for them forgiveness and a great reward.",
     "ref": "Quran 33:35"},
]
