# -*- coding: utf-8 -*-
LIFE = [
    {"year":"570 CE","title":{"en":"Birth in Mecca","fr":"Naissance à La Mecque","es":"Nacimiento en La Meca"},
     "text":{"en":"Born into the noble tribe of Quraysh. His father died before his birth, his mother when he was six. Raised by his grandfather, then his uncle Abu Talib.",
             "fr":"Né dans la noble tribu de Quraysh. Son père mourut avant sa naissance, sa mère quand il avait six ans.",
             "es":"Nacido en la noble tribu de Quraysh. Su padre murió antes de su nacimiento, su madre cuando tenía seis años."}},
    {"year":"595 CE","title":{"en":"Marriage to Khadija","fr":"Mariage avec Khadija","es":"Matrimonio con Jadiya"},
     "text":{"en":"At 25, he married Khadija bint Khuwaylid — a wealthy, respected businesswoman 15 years his senior. She became the first believer and his greatest support.",
             "fr":"À 25 ans, il épousa Khadija bint Khuwaylid — une femme d'affaires riche et respectée. Elle devint la première croyante.",
             "es":"A los 25 años, se casó con Jadiya bint Juwaylid — una mujer de negocios rica y respetada. Se convirtió en la primera creyente."}},
    {"year":"610 CE","title":{"en":"The First Revelation","fr":"La Première Révélation","es":"La Primera Revelación"},
     "text":{"en":"At 40, meditating in the cave of Hira, the Angel Gabriel appeared with the first verses: 'Read in the name of your Lord who created.'",
             "fr":"À 40 ans, méditant dans la grotte de Hira, l'Ange Gabriel apparut avec les premiers versets : « Lis au nom de ton Seigneur qui a créé. »",
             "es":"A los 40 años, meditando en la cueva de Hira, el Ángel Gabriel apareció con los primeros versículos: 'Lee en el nombre de tu Señor que creó.'"}},
    {"year":"613 CE","title":{"en":"Public Preaching","fr":"Prédication Publique","es":"Predicación Pública"},
     "text":{"en":"He began calling the people of Mecca to worship the One God. The poor and the weak answered first. The powerful opposed him — persecuting and torturing his followers.",
             "fr":"Il commença à appeler les gens de La Mecque à adorer le Dieu Unique. Les pauvres répondirent d'abord. Les puissants s'y opposèrent.",
             "es":"Comenzó a llamar al pueblo de La Meca a adorar al Dios Único. Los pobres respondieron primero. Los poderosos se opusieron."}},
    {"year":"622 CE","title":{"en":"The Hijra to Medina","fr":"L'Hégire à Médine","es":"La Hégira a Medina"},
     "text":{"en":"Facing assassination, he migrated to Medina. There he established the first Muslim community — a constitution guaranteeing rights to Muslims, Jews, and pagans alike.",
             "fr":"Face à un complot, il émigra à Médine. Là, il établit la première communauté musulmane — une constitution garantissant les droits à tous.",
             "es":"Ante un complot, emigró a Medina. Allí estableció la primera comunidad musulmana — una constitución que garantizaba derechos a todos."}},
    {"year":"630 CE","title":{"en":"Return to Mecca","fr":"Retour à La Mecque","es":"Regreso a La Meca"},
     "text":{"en":"He returned to Mecca with 10,000 companions — but entered without a drop of blood shed. He forgave his persecutors: 'Go, you are free.'",
             "fr":"Il retourna à La Mecque avec 10 000 compagnons — mais entra sans verser une goutte de sang. Il pardonna à ses persécuteurs : « Allez, vous êtes libres. »",
             "es":"Regresó a La Meca con 10.000 compañeros — pero entró sin derramar una gota de sangre. Perdonó a sus perseguidores: 'Id, sois libres.'"}},
    {"year":"632 CE","title":{"en":"Farewell & Death","fr":"Adieu et Mort","es":"Despedida y Muerte"},
     "text":{"en":"In his farewell sermon, he proclaimed: 'No Arab is superior to a non-Arab, nor white to black, except by piety.' He passed away in Medina with no gold, no palace — only a message.",
             "fr":"Dans son sermon d'adieu, il proclama : « Aucun Arabe n'est supérieur à un non-Arabe, ni un blanc à un noir, sauf par la piété. »",
             "es":"En su sermón de despedida, proclamó: 'Ningún árabe es superior a un no árabe, ni el blanco al negro, excepto por la piedad.'"}},
]

CHARACTER = [
    {"icon":"✓","title":{"en":"Truthfulness","fr":"Véracité","es":"Veracidad"},
     "text":{"en":"Even before prophethood, he was called Al-Amin — 'the Trustworthy.' His enemies testified to his honesty. Abu Sufyan, still a pagan, admitted to the Roman Emperor: 'He never lies.'",
             "fr":"Avant même la prophétie, on l'appelait Al-Amin — « le digne de confiance ». Ses ennemis témoignaient de son honnêteté.",
             "es":"Incluso antes de la profecía, era llamado Al-Amin — 'el Confiable'. Sus enemigos testificaban de su honestidad."}},
    {"icon":"🤲","title":{"en":"Mercy","fr":"Miséricorde","es":"Misericordia"},
     "text":{"en":"When the people of Ta'if stoned him until his feet bled, he prayed: 'O Allah, guide my people, for they do not know.' He forbade killing women, children, monks, and the elderly in war.",
             "fr":"Quand les gens de Ta'if le lapidèrent, il pria : « Ô Allah, guide mon peuple, car ils ne savent pas. »",
             "es":"Cuando la gente de Ta'if lo apedreó, oró: 'Oh Allah, guía a mi pueblo, pues no saben.'"}},
    {"icon":"🕊","title":{"en":"Humility","fr":"Humilité","es":"Humildad"},
     "text":{"en":"A king and a prophet — yet he mended his own sandals, milked his goat, and sat with the poor. A companion said: 'He was like one of us.'",
             "fr":"Un roi et un prophète — pourtant il réparait ses sandales, trayait sa chèvre et s'asseyait avec les pauvres.",
             "es":"Un rey y profeta — sin embargo remendaba sus sandalias, ordeñaba su cabra y se sentaba con los pobres."}},
    {"icon":"⚖","title":{"en":"Justice","fr":"Justice","es":"Justicia"},
     "text":{"en":"He said: 'If Fatima, daughter of Muhammad, stole, I would cut off her hand.' Justice was above kinship. Status never shielded the guilty.",
             "fr":"Il dit : « Si Fatima, fille de Muhammad, volait, je lui couperais la main. » La justice primait sur la parenté.",
             "es":"Dijo: 'Si Fátima, hija de Muhammad, robara, le cortaría la mano.' La justicia estaba por encima del parentesco."}},
    {"icon":"🎁","title":{"en":"Generosity","fr":"Générosité","es":"Generosidad"},
     "text":{"en":"He never refused a request. He gave away everything until he had nothing to give. A Bedouin once pulled his cloak roughly — he turned and gave him what he asked.",
             "fr":"Il ne refusait jamais une demande. Il donnait tout jusqu'à ne plus rien avoir à donner.",
             "es":"Nunca rechazaba una petición. Daba todo hasta no tener nada que dar."}},
    {"icon":"🌱","title":{"en":"Patience","fr":"Patience","es":"Paciencia"},
     "text":{"en":"He buried six of his seven children. Insulted, exiled, starved, attacked — yet never once did he retaliate for himself.",
             "fr":"Il enterra six de ses sept enfants. Insulté, exilé, affamé, attaqué — jamais il ne riposta pour lui-même.",
             "es":"Enterró a seis de sus siete hijos. Insultado, exiliado, hambriento, atacado — jamás se vengó por sí mismo."}},
    {"icon":"📖","title":{"en":"Devotion","fr":"Dévotion","es":"Devoción"},
     "text":{"en":"He would stand in night prayer until his feet swelled. His wife Aisha said: 'His character was the Quran.'",
             "fr":"Il se tenait en prière nocturne jusqu'à ce que ses pieds enflent. Sa femme Aisha dit : « Son caractère était le Coran. »",
             "es":"Se paraba en oración nocturna hasta que sus pies se hinchaban. Su esposa Aisha dijo: 'Su carácter era el Corán.'"}},
    {"icon":"❤","title":{"en":"Tenderness","fr":"Tendresse","es":"Ternura"},
     "text":{"en":"He kissed his grandchildren in public. He stopped prayer to comfort a crying child. He said: 'The best of you is the best to his family.'",
             "fr":"Il embrassait ses petits-enfants en public. Il interrompait la prière pour consoler un enfant qui pleurait.",
             "es":"Besaba a sus nietos en público. Detenía la oración para consolar a un niño que lloraba."}},
]

TESTIMONIES = [
    {"name":"Michael H. Hart","source":"The 100 (1978)",
     "quote":{"en":"He was the only man in history who was supremely successful on both the religious and secular levels.",
              "fr":"Il fut le seul homme de l'histoire à avoir connu un succès suprême sur les plans religieux et séculier.",
              "es":"Fue el único hombre en la historia que tuvo un éxito supremo tanto en el nivel religioso como en el secular."}},
    {"name":"George Bernard Shaw","source":"The Genuine Islam (1936)",
     "quote":{"en":"I believe that if a man like him were to assume the dictatorship of the modern world, he would succeed in solving its problems in a way that would bring it the much-needed peace and happiness.",
              "fr":"Je crois que si un homme comme lui dirigeait le monde moderne, il réussirait à résoudre ses problèmes d'une manière qui apporterait la paix.",
              "es":"Creo que si un hombre como él dirigiera el mundo moderno, lograría resolver sus problemas de una manera que traería la paz."}},
    {"name":"Mahatma Gandhi","source":"Young India (1924)",
     "quote":{"en":"I wanted to know the best of the life of one who holds today an undisputed sway over the hearts of millions of mankind.",
              "fr":"Je voulais connaître le meilleur de la vie de celui qui exerce aujourd'hui une influence incontestée sur les cœurs de millions d'êtres humains.",
              "es":"Quería conocer lo mejor de la vida de aquel que hoy ejerce una influencia indiscutible sobre los corazones de millones."}},
    {"name":"W. Montgomery Watt","source":"Muhammad: Prophet and Statesman (1961)",
     "quote":{"en":"His readiness to undergo persecution for his beliefs, the high moral character of the men who believed in him... all argue his fundamental integrity.",
              "fr":"Sa disposition à subir la persécution pour ses croyances, le haut caractère moral des hommes qui croyaient en lui... tout plaide pour son intégrité fondamentale.",
              "es":"Su disposición a sufrir persecución por sus creencias, el alto carácter moral de los hombres que creyeron en él... todo argumenta su integridad fundamental."}},
    {"name":"Alphonse de Lamartine","source":"Histoire de la Turquie (1854)",
     "quote":{"en":"Philosopher, orator, apostle, legislator, warrior, conqueror of ideas... is there any man greater than he?",
              "fr":"Philosophe, orateur, apôtre, législateur, guerrier, conquérant des idées... est-il un homme plus grand que lui ?",
              "es":"Filósofo, orador, apóstol, legislador, guerrero, conquistador de ideas... ¿hay algún hombre más grande que él?"}},
    {"name":"Annie Besant","source":"The Life and Teachings of Muhammad (1932)",
     "quote":{"en":"It is impossible for anyone who studies the life and character of the great Prophet of Arabia... to feel anything but reverence for that mighty Prophet.",
              "fr":"Il est impossible pour quiconque étudie la vie et le caractère du grand Prophète d'Arabie... de ne pas ressentir de la vénération pour ce puissant Prophète.",
              "es":"Es imposible para cualquiera que estudie la vida y el carácter del gran Profeta de Arabia... no sentir reverencia por ese poderoso Profeta."}},
]

NON_MUSLIMS = [
    {"icon":"📜","title":{"en":"The Charter of Medina","fr":"La Charte de Médine","es":"La Carta de Medina"},
     "text":{"en":"After arriving in Medina, he drafted a constitution granting Jews and Muslims equal rights, mutual defense, and freedom of religion.",
             "fr":"Après son arrivée à Médine, il rédigea une constitution accordant aux juifs et aux musulmans des droits égaux.",
             "es":"Tras llegar a Medina, redactó una constitución que otorgaba a judíos y musulmanes derechos iguales."}},
    {"icon":"⛪","title":{"en":"The Christians of Najran","fr":"Les Chrétiens de Najran","es":"Los Cristianos de Najrán"},
     "text":{"en":"A Christian delegation from Najran came to discuss religion. He welcomed them into his mosque and let them pray there, facing east.",
             "fr":"Une délégation chrétienne de Najran vint discuter de religion. Il les accueillit dans sa mosquée et les laissa y prier.",
             "es":"Una delegación cristiana de Najrán vino a discutir de religión. Los recibió en su mezquita y les permitió orar allí."}},
    {"icon":"🕊","title":{"en":"Protection of the Dhimmi","fr":"Protection des Dhimmi","es":"Protección de los Dhimmi"},
     "text":{"en":"He said: 'Whoever harms a dhimmi has harmed me, and I will be his opponent on the Day of Judgment.' Their blood, wealth, and honor were sacred.",
             "fr":"Il dit : « Celui qui nuit à un dhimmi m'a nui, et je serai son adversaire au Jour du Jugement. »",
             "es":"Dijo: 'Quien daña a un dhimmi me ha dañado, y seré su oponente en el Día del Juicio.'"}},
    {"icon":"⚖","title":{"en":"Justice Across Faiths","fr":"Justice Entre les Fois","es":"Justicia Entre Fes"},
     "text":{"en":"When a Muslim wronged a Jew, he ruled in favor of the Jew. Justice was never conditioned on religion.",
             "fr":"Quand un musulman lésait un juif, il statuait en faveur du juif. La justice n'était jamais conditionnée par la religion.",
             "es":"Cuando un musulmán agraviaba a un judío, fallaba a favor del judío. La justicia nunca estaba condicionada por la religión."}},
    {"icon":"🤝","title":{"en":"Honoring the Elderly","fr":"Honorer les Aînés","es":"Honrar a los Ancianos"},
     "text":{"en":"A very old man came to him, and the Prophet ﷺ stood up to welcome him and offered him his own seat. He said: 'It is part of glorifying Allah to honor the elderly.'",
             "fr":"Un vieil homme vint à lui, et le Prophète ﷺ se leva pour l'accueillir et lui offrit son propre siège.",
             "es":"Un anciano vino a él, y el Profeta ﷺ se levantó para recibirlo y le ofreció su propio asiento."}},
    {"icon":"🍞","title":{"en":"Kindness to the Neighbor","fr":"Bonté envers le Voisin","es":"Bondad al Vecino"},
     "text":{"en":"He said: 'Gabriel kept advising me about the neighbor until I thought he would make him an heir.' He visited his Jewish neighbor when sick.",
             "fr":"Il dit : « Gabriel ne cessait de me recommander le voisin, au point que je crus qu'il allait en faire un héritier. »",
             "es":"Dijo: 'Gabriel no dejaba de recomendarme al vecino, hasta que pensé que lo haría heredero.'"}},
]

VERSES_ABOUT_HIM = [
    {"ar":"وَمَا أَرْسَلْنَاكَ إِلَّا رَحْمَةً لِّلْعَالَمِينَ",
     "en":"And We have not sent you, [O Muhammad], except as a mercy to the worlds.","ref":"Quran 21:107"},
    {"ar":"وَإِنَّكَ لَعَلَىٰ خُلُقٍ عَظِيمٍ",
     "en":"And indeed, you are of a great moral character.","ref":"Quran 68:4"},
    {"ar":"لَقَدْ جَاءَكُمْ رَسُولٌ مِّنْ أَنفُسِكُمْ عَزِيزٌ عَلَيْهِ مَا عَنِتُّمْ حَرِيصٌ عَلَيْكُم بِالْمُؤْمِنِينَ رَءُوفٌ رَّحِيمٌ",
     "en":"There has certainly come to you a Messenger from among yourselves. Grievous to him is what you suffer; he is concerned over you and to the believers is kind and merciful.",
     "ref":"Quran 9:128"},
    {"ar":"وَمَا أَرْسَلْنَاكَ إِلَّا مُبَشِّرًا وَنَذِيرًا",
     "en":"And We have not sent you except as a bringer of good tidings and a warner.","ref":"Quran 25:56"},
    {"ar":"فَبِمَا رَحْمَةٍ مِّنَ اللَّهِ لِنتَ لَهُمْ ۖ وَلَوْ كُنتَ فَظًّا غَلِيظَ الْقَلْبِ لَانفَضُّوا مِنْ حَوْلِكَ",
     "en":"So by mercy from Allah, you were lenient with them. And if you had been rude and harsh in heart, they would have disbanded from about you.",
     "ref":"Quran 3:159"},
    {"ar":"يَا أَيُّهَا النَّبِيُّ إِنَّا أَرْسَلْنَاكَ شَاهِدًا وَمُبَشِّرًا وَنَذِيرًا",
     "en":"O Prophet, indeed We have sent you as a witness and a bringer of good tidings and a warner.",
     "ref":"Quran 33:45"},
]
