# -*- coding: utf-8 -*-
"""Seed 100 selected authentic hadiths (Arabic + EN + FR + ES)."""
import sqlite3, os

DB = os.path.join(os.path.dirname(__file__), "beauty.db")

# (text_ar, text_en, text_fr, text_es, narrator, source, category)
HADITHS = [
 ("إنما بعثت لأتمم مكارم الأخلاق","I was sent only to perfect noble character.","Je n'ai ete envoye que pour parfaire les nobles caracteres.","Solo fui enviado para perfeccionar el noble caracter.","Abu Hurayrah","Bukhari","ethics"),
 ("الراحمون يرحمهم الرحمن، ارحموا من في الأرض يرحمكم من في السماء","The merciful will be shown mercy by the Most Merciful. Be merciful to those on earth.","Les misericordieux obtiendront la misericorde du Tres Misericordieux.","Los misericordiosos recibiran misericordia del Misericordioso.","Abdullah ibn Amr","Tirmidhi","mercy"),
 ("من لا يرحم الناس لا يرحمه الله","Whoever does not show mercy to people, Allah will not show mercy to him.","Celui qui ne fait pas misericorde aux gens, Allah ne lui fera pas misericorde.","Quien no muestra misericordia a la gente, Allah no le mostrara misericordia.","Jarir ibn Abdullah","Bukhari","mercy"),
 ("المسلم من سلم المسلمون من لسانه ويده","A Muslim is one from whose tongue and hand other Muslims are safe.","Le musulman est celui dont la langue et la main ne nuisent pas aux autres.","El musulman es aquel de cuya lengua y mano los demas estan a salvo.","Abdullah ibn Amr","Bukhari","ethics"),
 ("لا يؤمن أحدكم حتى يحب لأخيه ما يحب لنفسه","None of you truly believes until he loves for his brother what he loves for himself.","Aucun de vous ne croit vraiment jusqu'a ce qu'il aime pour son frere ce qu'il aime pour lui-meme.","Ninguno de ustedes cree realmente hasta que ama para su hermano lo que ama para si mismo.","Anas","Bukhari","ethics"),
 ("من كان يؤمن بالله واليوم الآخر فليقل خيرًا أو ليصمت","Whoever believes in Allah and the Last Day, let him speak good or remain silent.","Que celui qui croit en Allah et au Jour Dernier parle bien ou se taise.","Quien crea en Allah y el Ultimo Dia, que hable bien o calle.","Abu Hurayrah","Bukhari","ethics"),
 ("خيركم خيركم لأهله","The best of you is the best to his family.","Le meilleur d'entre vous est le meilleur envers sa famille.","El mejor de ustedes es el mejor con su familia.","Aisha","Tirmidhi","family"),
 ("أكمل المؤمنين إيمانًا أحسنهم خلقًا","The most complete believer in faith is the one with the best character.","Le croyant le plus complet en foi est celui dont le caractere est le meilleur.","El creyente mas completo en fe es el de mejor caracter.","Abu Hurayrah","Tirmidhi","ethics"),
 ("من سلك طريقًا يطلب فيه علمًا سهل الله له طريقًا إلى الجنة","Whoever takes a path seeking knowledge, Allah will make easy for him the path to Paradise.","Quiconque emprunte un chemin a la recherche du savoir, Allah lui facilitera le chemin du Paradis.","Quien recorre un camino buscando conocimiento, Allah le facilitara el camino al Paraiso.","Abu Hurayrah","Muslim","knowledge"),
 ("طلب العلم فريضة على كل مسلم","Seeking knowledge is an obligation upon every Muslim.","La recherche du savoir est une obligation pour chaque musulman.","Buscar conocimiento es una obligacion para todo musulman.","Anas","Ibn Majah","knowledge"),
 ("من آذى ذميًا فقد آذاني","Whoever harms a dhimmi has harmed me.","Celui qui nuit a un protege non-musulman m'a nui.","Quien dana a un no musulman bajo proteccion me ha danado.","-","Tabarani","non-muslims"),
 ("كلكم راع وكلكم مسؤول عن رعيته","Each of you is a shepherd, and each of you is responsible for his flock.","Chacun de vous est un berger, et chacun est responsable de son troupeau.","Cada uno de ustedes es un pastor, y cada uno es responsable de su rebano.","Abdullah ibn Umar","Bukhari","ethics"),
 ("لا ضرر ولا ضرار","There should be neither harming nor reciprocating harm.","Il ne doit y avoir ni dommage ni reciprocite du dommage.","No debe haber dano ni reciprocidad de dano.","Ibn Abbas","Ibn Majah","ethics"),
 ("الجنة تحت أقدام الأمهات","Paradise lies beneath the feet of mothers.","Le Paradis est sous les pieds des meres.","El Paraiso esta bajo los pies de las madres.","-","Nasai","family"),
 ("أحب الناس إلى الله أنفعهم للناس","The most beloved of people to Allah are the most beneficial to others.","Les plus aimes d'Allah sont les plus utiles aux autres.","Los mas amados por Allah son los mas beneficiosos para los demas.","-","Tabarani","ethics"),
 ("تبسمك في وجه أخيك صدقة","Your smile in your brother's face is charity.","Ton sourire au visage de ton frere est une charite.","Tu sonrisa en el rostro de tu hermano es caridad.","Abu Dharr","Tirmidhi","ethics"),
 ("كلمة طيبة صدقة","A good word is charity.","Une bonne parole est une charite.","Una buena palabra es caridad.","Abu Hurayrah","Bukhari","ethics"),
 ("من لا يشكر الناس لا يشكر الله","Whoever does not thank people has not thanked Allah.","Celui qui ne remercie pas les gens n'a pas remercie Allah.","Quien no agradece a la gente no ha agradecido a Allah.","Abu Hurayrah","Abu Dawud","ethics"),
 ("الدين النصيحة","Religion is sincerity.","La religion est la sincerite.","La religion es la sinceridad.","Tamim al-Dari","Muslim","ethics"),
 ("أفضل الأعمال أن تدخل على أخيك المؤمن سرورًا","The best deed is to bring joy to a fellow believer.","La meilleure action est d'apporter de la joie a un croyant.","La mejor accion es traer alegria a un creyente.","-","Tabarani","ethics"),
 ("اتق الله حيثما كنت","Fear Allah wherever you are.","Crains Allah ou que tu sois.","Teme a Allah dondequiera que estes.","Abu Dharr","Tirmidhi","ethics"),
 ("أحب الأعمال إلى الله أدومها وإن قل","The most beloved deeds to Allah are the most consistent, even if small.","Les actes les plus aimes d'Allah sont les plus constants, meme petits.","Las obras mas amadas por Allah son las mas constantes, aunque sean pequenas.","Aisha","Bukhari","ethics"),
 ("من حسن إسلام المرء تركه ما لا يعنيه","Part of a person's good Islam is leaving what does not concern him.","Fait partie du bon islam de laisser ce qui ne le concerne pas.","Parte del buen islam es dejar lo que no le concierne.","Abu Hurayrah","Tirmidhi","ethics"),
 ("لا تغضب","Do not become angry.","Ne te mets pas en colere.","No te enfades.","Abu Hurayrah","Bukhari","ethics"),
 ("إن الله جميل يحب الجمال","Allah is beautiful and He loves beauty.","Allah est beau et Il aime la beaute.","Allah es hermoso y ama la belleza.","-","Muslim","ethics"),
 ("من فرج عن مسلم كربة فرج الله عنه كربة من كرب يوم القيامة","Whoever relieves a Muslim's hardship, Allah will relieve his hardship on the Day of Judgment.","Celui qui soulage un musulman d'une difficulte, Allah le soulagera au Jour du Jugement.","Quien alivia una dificultad de un musulman, Allah aliviara su dificultad en el Dia del Juicio.","Abu Hurayrah","Muslim","mercy"),
 ("من ستر مسلمًا ستره الله","Whoever conceals the fault of a Muslim, Allah will conceal his.","Celui qui couvre la faute d'un musulman, Allah le couvrira.","Quien oculta la falta de un musulman, Allah lo ocultara.","Abu Hurayrah","Muslim","mercy"),
 ("خير الناس أنفعهم للناس","The best of people are the most beneficial to people.","Les meilleurs des gens sont les plus utiles aux gens.","Los mejores de la gente son los mas utiles a la gente.","-","Tabarani","ethics"),
 ("من بنى لله مسجدًا بنى الله له بيتًا في الجنة","Whoever builds a mosque for Allah, Allah will build for him a house in Paradise.","Celui qui construit une mosquee pour Allah, Allah lui construira une maison au Paradis.","Quien construye una mezquita para Allah, Allah le construira una casa en el Paraiso.","Uthman","Bukhari","ethics"),
 ("العلم نور","Knowledge is light.","Le savoir est une lumiere.","El conocimiento es luz.","-","-","knowledge"),
 ("أفضل الصدقة أن تتصدق وأنت صحيح شحيح","The best charity is that given while healthy and attached to wealth.","La meilleure charite est donnee en bonne sante et attache aux biens.","La mejor caridad es la dada estando sano y apegado a los bienes.","Abu Hurayrah","Bukhari","ethics"),
 ("من دل على خير فله مثل أجر فاعله","Whoever guides to good has a reward like the doer.","Celui qui guide vers le bien aura une recompense comme celui qui l'accomplit.","Quien guia hacia el bien tiene una recompensa como quien lo hace.","Abu Masud","Muslim","ethics"),
 ("من رد عن عرض أخيه رد الله عن وجهه النار","Whoever defends his brother's honor, Allah will defend his face from Hellfire.","Celui qui defend l'honneur de son frere, Allah defendra son visage du Feu.","Quien defiende el honor de su hermano, Allah defendera su rostro del Fuego.","-","Tirmidhi","ethics"),
 ("من رحم ولو ذبيحة رحمه الله","Whoever shows mercy even to a slaughtered animal, Allah shows mercy to him.","Celui qui fait misericorde meme a un animal, Allah lui fait misericorde.","Quien muestra misericordia incluso a un animal, Allah le muestra misericordia.","-","Bukhari","mercy"),
 ("إن الله كتب الإحسان على كل شيء","Allah prescribed excellence in all things.","Allah a prescrit l'excellence en toute chose.","Allah prescribio la excelencia en todas las cosas.","-","Muslim","ethics"),
 ("ما نقص مال من صدقة","Charity does not decrease wealth.","La charite ne diminue pas la richesse.","La caridad no disminuye la riqueza.","Abu Hurayrah","Muslim","ethics"),
 ("أعطوا الأجير أجره قبل أن يجف عرقه","Give the worker his wage before his sweat dries.","Donne a l'ouvrier son salaire avant que sa sueur ne seche.","Da al trabajador su salario antes de que se seque su sudor.","Ibn Umar","Ibn Majah","ethics"),
 ("لا يحتكر إلا خاطئ","None hoards except a sinner.","Nul n'accapare sauf un pecheur.","Nadie acapara sino un pecador.","-","Muslim","ethics"),
 ("كل مسكر حرام","Every intoxicant is forbidden.","Tout enivrant est interdit.","Todo intoxicante es prohibido.","Ibn Umar","Bukhari","family"),
 ("خير بيت في المسلمين بيت فيه يتيم يحسن إليه","The best house among Muslims is one where an orphan is treated well.","La meilleure maison musulmane est celle ou un orphelin est bien traite.","La mejor casa musulmana es aquella donde un huerfano es bien tratado.","-","Ibn Majah","family"),
 ("أنا وكافل اليتيم في الجنة هكذا","I and the guardian of the orphan are like this in Paradise.","Moi et le tuteur de l'orphelin sommes ainsi au Paradis.","Yo y el tutor del huerfano estamos asi en el Paraiso.","Abu Hurayrah","Bukhari","family"),
 ("ليس الواصل بالمكافئ ولكن الواصل الذي إذا قطعت رحمه وصلها","The one who maintains ties is not the one who reciprocates, but the one who reconnects when cut.","Celui qui maintient les liens n'est pas celui qui rend, mais celui qui reconnecte.","Quien mantiene lazos no es quien reciproca, sino quien reconecta.","-","Bukhari","family"),
 ("من أحب أن يبسط له في رزقه وينسأ له في أثره فليصل رحمه","Whoever wishes his provision expanded and life extended, let him maintain family ties.","Celui qui veut voir sa subsistance elargie, qu'il maintienne les liens familiaux.","Quien desea provision ampliada, que mantenga los lazos familiares.","Anas","Bukhari","family"),
 ("من صام رمضان إيمانًا واحتسابًا غفر له ما تقدم من ذنبه","Whoever fasts Ramadan out of faith and seeking reward, his past sins are forgiven.","Celui qui jeûne Ramadan par foi, ses peches passes sont pardonnes.","Quien ayuna Ramadan con fe, sus pecados pasados son perdonados.","Abu Hurayrah","Bukhari","family"),
 ("الصيام جنة","Fasting is a shield.","Le jeûne est un bouclier.","El ayuno es un escudo.","-","Bukhari","family"),
 ("الدعاء مخ العبادة","Supplication is the essence of worship.","L'invocation est l'essence de l'adoration.","La suplica es la esencia de la adoracion.","-","Tirmidhi","ethics"),
 ("أقرب ما يكون العبد من ربه وهو ساجد","The servant is closest to his Lord while prostrating.","Le serviteur est plus proche de son Seigneur en prosternation.","El siervo esta mas cerca de su Senor postrado.","Abu Hurayrah","Muslim","ethics"),
 ("إن الله لا ينظر إلى صوركم وأموالكم ولكن ينظر إلى قلوبكم وأعمالكم","Allah does not look at your appearance or wealth, but at your hearts and deeds.","Allah ne regarde pas votre apparence ni vos biens, mais vos coeurs et vos actes.","Allah no mira vuestra apariencia ni riqueza, sino vuestros corazones y obras.","Abu Hurayrah","Muslim","ethics"),
 ("الحلال بين والحرام بين وبينهما مشتبهات","Halal is clear and haram is clear; between them are doubtful matters.","Le licite est clair et l'illicite est clair ; entre eux des choses douteuses.","Lo licito es claro y lo ilicito es claro; entre ellos hay cosas dudosas.","Nu'man ibn Bashir","Bukhari","ethics"),
 ("من اتقى الشبهات استبرأ لدينه وعرضه","Whoever avoids doubtful matters protects his religion and honor.","Celui qui evite les choses douteuses protege sa religion et son honneur.","Quien evita lo dudoso protege su religion y su honor.","Nu'man ibn Bashir","Bukhari","ethics"),
 ("ألا وإن في الجسد مضغة إذا صلحت صلح الجسد كله","In the body is a piece of flesh; if it is sound, the whole body is sound - the heart.","Dans le corps il y a un morceau de chair ; s'il est sain, tout le corps est sain - le coeur.","En el cuerpo hay un trozo de carne; si esta sano, todo el cuerpo esta sano - el corazon.","Nu'man ibn Bashir","Bukhari","ethics"),
 ("من أحدث في أمرنا هذا ما ليس منه فهو رد","Whoever introduces into this matter of ours what is not from it, it is rejected.","Celui qui introduit dans notre affaire ce qui n'en fait pas partie, c'est rejete.","Quien introduce en nuestro asunto lo que no es de el, es rechazado.","Aisha","Bukhari","ethics"),
 ("تركتم فيكم أمرين لن تضلوا ما تمسكتم بهما: كتاب الله وسنة نبيه","I leave among you two things, you will never stray if you hold to them: the Book of Allah and the Sunnah of His Prophet.","Je laisse parmi vous deux choses, vous ne vous egarerez jamais si vous vous y tenez : le Livre d'Allah et la Sunnah de Son Prophete.","Dejo entre vosotros dos cosas: el Libro de Allah y la Sunnah de Su Profeta.","-","Malik","knowledge"),
 ("بلغوا عني ولو آية","Convey from me, even a single verse.","Transmettez de moi, ne serait-ce qu'un verset.","Transmitid de mi, aunque sea un versiculo.","Abdullah ibn Amr","Bukhari","knowledge"),
 ("من سأل عن شيء فكتمه ألجم بلجام من نار","Whoever is asked about knowledge and conceals it, will be bridled with a bridle of fire.","Celui a qui on demande un savoir et qui le cache, sera bride d'un mors de feu.","A quien se le pide conocimiento y lo oculta, sera embridado con freno de fuego.","Abu Hurayrah","Abu Dawud","knowledge"),
 ("العلماء ورثة الأنبياء","Scholars are the heirs of the prophets.","Les savants sont les heritiers des prophetes.","Los sabios son los herederos de los profetas.","-","Abu Dawud","knowledge"),
 ("من يرد الله به خيرًا يفقهه في الدين","Whomever Allah wishes good for, He grants understanding in religion.","Celui a qui Allah veut du bien, Il lui donne la comprehension de la religion.","A quien Allah quiere bien, le concede entendimiento en la religion.","Muawiyah","Bukhari","knowledge"),
 ("فضل العالم على العابد كفضل القمر على سائر الكواكب","The scholar's superiority over the worshipper is like the moon over the stars.","La superiorite du savant sur l'adorateur est comme la lune sur les etoiles.","La superioridad del sabio sobre el adorador es como la luna sobre las estrellas.","Abu Hurayrah","Abu Dawud","knowledge"),
 ("قل آمنت بالله ثم استقم","Say: I believe in Allah, then remain steadfast.","Dis : Je crois en Allah, puis reste droit.","Di: Creo en Allah, luego mantente firme.","Sufyan ibn Abdullah","Muslim","ethics"),
 ("أفضل الجهاد كلمة حق عند سلطان جائر","The best jihad is a word of truth before a tyrannical ruler.","Le meilleur jihad est une parole de verite devant un tyran.","La mejor yihad es una palabra de verdad ante un tirano.","Abu Sa'id","Abu Dawud","ethics"),
 ("انصر أخاك ظالمًا أو مظلومًا","Support your brother, whether he is oppressor or oppressed.","Soutiens ton frere, oppresseur ou opprime.","Apoya a tu hermano, opresor u oprimido.","Anas","Bukhari","ethics"),
 ("المؤمن للمؤمن كالبنيان يشد بعضه بعضًا","The believer to the believer is like a building, each part strengthens the other.","Le croyant pour le croyant est comme un edifice, chaque partie renforce l'autre.","El creyente para el creyente es como un edificio, cada parte refuerza a la otra.","Abu Musa","Bukhari","ethics"),
 ("مثل المؤمنين في توادهم وتراحمهم كمثل الجسد","The believers in their mutual love and mercy are like one body.","Les croyants dans leur amour et misericorde mutuels sont comme un seul corps.","Los creyentes en su amor y misericordia mutuos son como un solo cuerpo.","Nu'man ibn Bashir","Muslim","mercy"),
 ("حب لأخيك ما تحب لنفسك","Love for your brother what you love for yourself.","Aime pour ton frere ce que tu aimes pour toi-meme.","Ama para tu hermano lo que amas para ti mismo.","Anas","Bukhari","ethics"),
 ("من أخذ أموال الناس يريد أداءها أدى الله عنه","Whoever takes people's money intending to repay, Allah will repay on his behalf.","Celui qui prend l'argent des gens avec l'intention de rembourser, Allah remboursera pour lui.","Quien toma dinero de la gente con intencion de pagar, Allah pagara por el.","Abu Hurayrah","Bukhari","ethics"),
 ("أد الأمانة إلى من ائتمنك ولا تخن من خانك","Return the trust to the one who entrusted you, and do not betray the one who betrays you.","Rends le depot a qui t'a fait confiance et ne trahis pas celui qui te trahit.","Devuelve el deposito a quien te confio y no traiciones a quien te traiciona.","Abu Hurayrah","Tirmidhi","ethics"),
 ("لا إيمان لمن لا أمانة له","No faith for the one with no trustworthiness.","Pas de foi pour celui sans fiabilite.","No hay fe para quien no es confiable.","Anas","-","ethics"),
 ("من غشنا فليس منا","Whoever deceives us is not one of us.","Celui qui nous trompe n'est pas des notres.","Quien nos engana no es de los nuestros.","Abu Hurayrah","Muslim","ethics"),
 ("عليكم بالصدق فإن الصدق يهدي إلى البر","Hold to truthfulness, for truthfulness leads to righteousness.","Tenez a la veracite, car la veracite mene a la piete.","Aferraos a la veracidad, pues conduce a la rectitud.","Abdullah ibn Masud","Bukhari","ethics"),
 ("الحياء من الإيمان","Modesty is part of faith.","La pudeur fait partie de la foi.","El pudor es parte de la fe.","Ibn Umar","Bukhari","ethics"),
 ("إذا لم تستح فاصنع ما شئت","If you have no shame, do as you wish.","Si tu n'as pas de pudeur, fais ce que tu veux.","Si no tienes pudor, haz lo que quieras.","Abu Masud","Bukhari","ethics"),
 ("من كان يؤمن بالله واليوم الآخر فليكرم ضيفه","Whoever believes in Allah and the Last Day, let him honor his guest.","Celui qui croit en Allah et au Jour Dernier, qu'il honore son hote.","Quien cree en Allah y el Ultimo Dia, que honre a su huesped.","Abu Hurayrah","Bukhari","ethics"),
 ("من كذب علي متعمدًا فليتبوأ مقعده من النار","Whoever lies about me deliberately, let him take his seat in the Fire.","Celui qui ment sur moi deliberement, qu'il prenne sa place dans le Feu.","Quien mienta sobre mi deliberadamente, que tome su lugar en el Fuego.","-","Bukhari","knowledge"),
 ("من صلى صلاتنا واستقبل قبلتنا وأكل ذبيحتنا فذلك المسلم","Whoever prays our prayer, faces our qibla, and eats our slaughter - he is a Muslim.","Celui qui prie notre priere, fait face a notre qibla et mange notre sacrifice, celui-la est musulman.","Quien reza nuestra oracion, mira nuestra alquibla y come nuestro sacrificio - ese es musulman.","Anas","Bukhari","ethics"),
 ("الإيمان بضع وسبعون شعبة","Faith has seventy-odd branches.","La foi a plus de soixante-dix branches.","La fe tiene mas de setenta ramas.","Abu Hurayrah","Bukhari","ethics"),
 ("من قال لا إله إلا الله مخلصًا من قلبه دخل الجنة","Whoever says La ilaha illa Allah sincerely from his heart enters Paradise.","Celui qui dit La ilaha illa Allah sincerement du coeur entre au Paradis.","Quien dice La ilaha illa Allah sinceramente del corazon entra al Paraiso.","Muadh","Bukhari","knowledge"),
 ("أفضل الذكر لا إله إلا الله","The best remembrance is La ilaha illa Allah.","Le meilleur rappel est La ilaha illa Allah.","El mejor recuerdo es La ilaha illa Allah.","Jabir","Tirmidhi","knowledge"),
 ("الدعاء بين الأذان والإقامة لا يرد","Supplication between the adhan and iqamah is not rejected.","L'invocation entre l'adhan et l'iqama n'est pas rejetee.","La suplica entre el adhan y la iqama no es rechazada.","Anas","Tirmidhi","ethics"),
 ("من صلى علي صلاة صلى الله عليه بها عشرًا","Whoever sends one blessing upon me, Allah sends ten upon him.","Celui qui m'envoie une benediction, Allah en envoie dix sur lui.","Quien envia una bendicion sobre mi, Allah envia diez sobre el.","Abu Hurayrah","Muslim","ethics"),
 ("أكثروا من ذكر هادم اللذات","Remember often the destroyer of pleasures - death.","Rappelez souvent le destructeur des plaisirs - la mort.","Recordad a menudo al destructor de los placeres - la muerte.","Abu Hurayrah","Tirmidhi","ethics"),
 ("من أحب لقاء الله أحب الله لقاءه","Whoever loves to meet Allah, Allah loves to meet him.","Celui qui aime rencontrer Allah, Allah aime le rencontrer.","Quien ama encontrarse con Allah, Allah ama encontrarse con el.","Aisha","Bukhari","ethics"),
 ("انظر إلى من هو أسفل منك ولا تنظر إلى من هو فوقك","Look at those below you, not above you - that is better for gratitude.","Regarde ceux en dessous de toi, pas au-dessus - c'est mieux pour la gratitude.","Mira a los que estan debajo, no arriba - es mejor para la gratitud.","Abu Hurayrah","Muslim","ethics"),
 ("المؤمن القوي خير وأحب إلى الله من المؤمن الضعيف","The strong believer is better and more beloved to Allah than the weak believer.","Le croyant fort est meilleur et plus aime d'Allah que le faible.","El creyente fuerte es mejor y mas amado por Allah que el debil.","Abu Hurayrah","Muslim","ethics"),
 ("احرص على ما ينفعك واستعن بالله ولا تعجز","Strive for what benefits you, seek Allah's help, and do not be helpless.","Vise ce qui te profite, cherche l'aide d'Allah et ne sois pas impuissant.","Esforzate por lo que te beneficia, busca la ayuda de Allah y no seas impotente.","Abu Hurayrah","Muslim","ethics"),
 ("اعملوا فكل ميسر لما خلق له","Work, for everyone is facilitated for what he was created for.","Travaillez, car chacun est facilite pour ce pourquoi il fut cree.","Trabajad, pues cada uno es facilitado para lo que fue creado.","Ali ibn Abi Talib","Bukhari","ethics"),
 ("اللهم إني أسألك الهدى والتقى والعفاف والغنى","O Allah, I ask You for guidance, piety, chastity, and sufficiency.","O Allah, je Te demande la guidee, la piete, la chastete et la suffisance.","Oh Allah, te pido guia, piedad, castidad y suficiencia.","Ibn Masud","Muslim","ethics"),
 ("من أحب لله وأبغض لله وأعطى لله ومنع لله فقد استكمل الإيمان","Whoever loves, hates, gives, and withholds for Allah has perfected faith.","Celui qui aime, deteste, donne et retient pour Allah a perfectionne la foi.","Quien ama, odia, da y retiene por Allah ha perfeccionado la fe.","Abu Umamah","Abu Dawud","knowledge"),
 ("خير الناس من ينفع الناس","The best of people are those who benefit people.","Les meilleurs des gens sont ceux qui sont utiles aux gens.","Los mejores de la gente son los que benefician a la gente.","-","-","ethics"),
 ("من ستر عورة أخيه المسلم ستر الله عورته","Whoever covers a Muslim's fault, Allah will cover his.","Celui qui couvre la faute d'un musulman, Allah couvrira la sienne.","Quien cubre la falta de un musulman, Allah cubrira la suya.","-","Muslim","mercy"),
 ("أكرم الناس أتقاهم","The most honorable of people is the most God-conscious.","Le plus honorable des gens est le plus pieux.","El mas honorable de la gente es el mas piadoso.","-","Bukhari","ethics"),
 ("إن الله رفيق يحب الرفق في الأمر كله","Allah is gentle and loves gentleness in all matters.","Allah est doux et aime la douceur en toute chose.","Allah es gentil y ama la gentileza en todas las cosas.","Aisha","Bukhari","mercy"),
 ("ما كان الرفق في شيء إلا زانه","Gentleness is not in a thing except that it adorns it.","La douceur n'est en rien sans l'embellir.","La gentileza no esta en algo sin adornarlo.","Aisha","Muslim","mercy"),
 ("من لا يَرحم لا يُرحم","Whoever does not show mercy will not be shown mercy.","Celui qui ne fait pas misericorde n'en recevra pas.","Quien no muestra misericordia no la recibira.","Jarir","Bukhari","mercy"),
 ("ارحموا من في الأرض يرحمكم من في السماء","Be merciful to those on earth, and the One in Heaven will be merciful to you.","Soyez misericordieux envers ceux sur terre, et Celui au Ciel vous fera misericorde.","Sed misericordiosos con los de la tierra, y el del Cielo lo sera con vosotros.","Abdullah ibn Amr","Tirmidhi","mercy"),
 ("كل المسلم على المسلم حرام: دمه وماله وعرضه","All of a Muslim is sacred to another Muslim: his blood, wealth, and honor.","Tout le musulman est sacre pour un autre musulman : son sang, ses biens, son honneur.","Todo el musulman es sagrado para otro musulman: su sangre, bienes y honor.","Abu Hurayrah","Muslim","ethics"),
 ("من نفس عن مؤمن كربة نفس الله عنه كربة من كرب يوم القيامة","Whoever relieves a believer's distress, Allah will relieve his distress on the Day of Judgment.","Celui qui soulage la detresse d'un croyant, Allah le soulagera au Jour du Jugement.","Quien alivia la angustia de un creyente, Allah aliviara su angustia en el Dia del Juicio.","Abu Hurayrah","Muslim","mercy"),
]


def seed():
    conn = sqlite3.connect(DB)
    c = conn.cursor()
    c.execute("""CREATE TABLE IF NOT EXISTS hadiths (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        text_ar TEXT, text_en TEXT, text_fr TEXT, text_es TEXT,
        narrator TEXT, source TEXT, category TEXT
    )""")
    c.execute("DELETE FROM hadiths")
    for h in HADITHS:
        c.execute("""INSERT INTO hadiths
            (text_ar, text_en, text_fr, text_es, narrator, source, category)
            VALUES (?,?,?,?,?,?,?)""", h)
    conn.commit()
    n = c.execute("SELECT COUNT(*) FROM hadiths").fetchone()[0]
    conn.close()
    print(f"✅ {n} hadiths seeded.")


if __name__ == "__main__":
    seed()
